STOCKS = {
    "360 ONE WAM LIMITED": "360ONE",
    "Aarti Industries Limited": "AARTIIND",
    "Aditya Birla Capital Limited": "ABCAPITAL",
    "Aditya Birla Fashion and Retail Limited": "ABFRL",
    "Adani Energy Solutions Limited": "ADANIENSOL",
    "Adani Enterprises Limited": "ADANIENT",
    "Adani Green Energy Limited": "ADANIGREEN",
    "Adani Ports and Special Economic Zone Limited": "ADANIPORTS",
    "Adani Power Limited": "ADANIPOWER",
    "Aegis Logistics Limited": "AEGISLOG",
    "Aegis Vopak Terminals Limited": "AEGISVOPAK",
    "Aeroflex Enterprises Limited": "AEROENTER",
    "Aeroflex Industries Limited": "AEROFLEX",
    "Afcons Infrastructure Limited": "AFCONS",
    "Akme Fintrade (India) Limited": "AFIL",
    "Allcargo Logistics Limited": "ALLCARGO",
    "Alok Industries Limited": "ALOKINDS",
    "Ambuja Cements Limited": "AMBUJACEM",
    "Anant Raj Limited": "ANANTRAJ",
    "Angel One Limited": "ANGELONE",
    "Apollo Micro Systems Limited": "APOLLO",
    "Apollo Tyres Limited": "APOLLOTYRE",
    "Aptus Value Housing Finance India Limited": "APTUS",
    "Arisinfra Solutions Limited": "ARISINFRA",
    "Arkade Developers Limited": "ARKADE",
    "Ashoka Buildcon Limited": "ASHOKA",
    "Ashok Leyland Limited": "ASHOKLEY",
    "Asian Paints Limited": "ASIANPAINT",
    "Aster DM Healthcare Limited": "ASTERDM",
    "Adani Total Gas Limited": "ATGL",
    "Ather Energy Limited": "ATHERENERG",
    "AU Small Finance Bank Limited": "AUBANK",
    "Aurobindo Pharma Limited": "AUROPHARMA",
    "Avantel Limited": "AVANTEL",
    "AWL Agri Business Limited": "AWL",
    "Axis Bank Limited": "AXISBANK",
    "Axita Cotton Limited": "AXITA",
    "Bajaj Consumer Care Limited": "BAJAJCON",
    "Bajaj Finserv Limited": "BAJAJFINSV",
    "Bajaj Housing Finance Limited": "BAJAJHFL",
    "Bajaj Hindusthan Sugar Limited": "BAJAJHIND",
    "Bajaj Finance Limited": "BAJFINANCE",
    "Bandhan Bank Limited": "BANDHANBNK",
    "Bank of Baroda": "BANKBARODA",
    "Bank of India": "BANKINDIA",
    "Bharat Dynamics Limited": "BDL",
    "Bharat Electronics Limited": "BEL",
    "Belrise Industries Limited": "BELRISE",
    "Bharat Forge Limited": "BHARATFORG",
    "Bharti Airtel Limited": "BHARTIARTL",
    "Bharat Heavy Electricals Limited": "BHEL",
    "Biocon Limited": "BIOCON",
    "BLS International Services Limited": "BLS",
    "Bluspring Enterprises Limited": "BLUSPRING",
    "Bombay Dyeing & Mfg Company Limited": "BOMDYEING",
    "Bharat Petroleum Corporation Limited": "BPCL",
    "BSE Limited": "BSE",
    "BIRLASOFT LIMITED": "BSOFT",
    "Bodhi Tree Multimedia Limited": "BTML",
    "Canara Bank": "CANBK",
    "Castrol India Limited": "CASTROLIND",
    "CCL Products (India) Limited": "CCL",
    "Central Depository Services (India) Limited": "CDSL",
    "Central Bank of India": "CENTRALBK",
    "CESC Limited": "CESC",
    "Capri Global Capital Limited": "CGCL",
    "CG Power and Industrial Solutions Limited": "CGPOWER",
    "Chambal Fertilizers & Chemicals Limited": "CHAMBLFERT",
    "Chennai Petroleum Corporation Limited": "CHENNPETRO",
    "Cholamandalam Investment and Finance Company Limited": "CHOLAFIN",
    "Cipla Limited": "CIPLA",
    "Coal India Limited": "COALINDIA",
    "Cochin Shipyard Limited": "COCHINSHIP",
    "Coforge Limited": "COFORGE",
    "Container Corporation of India Limited": "CONCOR",
    "Confidence Petroleum India Limited": "CONFIPET",
    "Coromandel International Limited": "COROMANDEL",
    "Crompton Greaves Consumer Electricals Limited": "CROMPTON",
    "City Union Bank Limited": "CUB",
    "Cupid Limited": "CUPID",
    "Dabur India Limited": "DABUR",
    "Dam Capital Advisors Limited": "DAMCAPITAL",
    "Data Patterns (India) Limited": "DATAPATTNS",
    "Davangere Sugar Company Limited": "DAVANGERE",
    "Valor Estate Limited": "DBREALTY",
    "DCB Bank Limited": "DCBBANK",
    "DCW Limited": "DCW",
    "DCX Systems Limited": "DCXINDIA",
    "Delhivery Limited": "DELHIVERY",
    "Delta Corp Limited": "DELTACORP",
    "Den Networks Limited": "DEN",
    "Devyani International Limited": "DEVYANI",
    "Dhanlaxmi Bank Limited": "DHANBANK",
    "Dhani Services Limited": "DHANI",
    "Diamond Power Infrastructure Limited": "DIACABS",
    "Digitide Solutions Limited": "DIGITIDE",
    "DLF Limited": "DLF",
    "Dr. Reddys Laboratories Limited": "DRREDDY",
    "Easy Trip Planners Limited": "EASEMYTRIP",
    "Edelweiss Financial Services Limited": "EDELWEISS",
    "Enviro Infra Engineers Limited": "EIEL",
    "Electrosteel Castings Limited": "ELECTCAST",
    "Ellenbarrie Industrial Gases Limited": "ELLEN",
    "Embassy Developments Limited": "EMBDL",
    "Electronics Mart India Limited": "EMIL",
    "Engineers India Limited": "ENGINERSIN",
    "Siemens Energy India Limited": "ENRIN",
    "Equitas Small Finance Bank Limited": "EQUITASBNK",
    "Integra Essentia Limited": "ESSENTIA",
    "ETERNAL LIMITED": "ETERNAL",
    "Excel Realty N Infra Limited": "EXCEL",
    "Exide Industries Limited": "EXIDEIND",
    "Fertilizers and Chemicals Travancore Limited": "FACT",
    "FCS Software Solutions Limited": "FCSSOFT",
    "The Federal Bank  Limited": "FEDERALBNK",
    "Filatex India Limited": "FILATEX",
    "Filatex Fashions Limited": "FILATFASH",
    "Fino Payments Bank Limited": "FINOPB",
    "Finolex Industries Limited": "FINPIPE",
    "Brainbees Solutions Limited": "FIRSTCRY",
    "Five-Star Business Finance Limited": "FIVESTAR",
    "Fortis Healthcare Limited": "FORTIS",
    "Firstsource Solutions Limited": "FSL",
    "Fusion Finance Limited": "FUSION",
    "Gujarat Ambuja Exports Limited": "GAEL",
    "GAIL (India) Limited": "GAIL",
    "GACM Technologies Limited": "GATECHDVR",
    "Gateway Distriparks Limited": "GATEWAY",
    "Genus Power Infrastructures Limited": "GENUSPOWER",
    "Geojit Financial Services Limited": "GEOJITFSL",
    "Globe Textiles (India) Limited": "GLOBE",
    "Gujarat Mineral Development Corporation Limited": "GMDCLTD",
    "GMR AIRPORTS LIMITED": "GMRAIRPORT",
    "GMR Power and Urban Infra Limited": "GMRP&UI",
    "Godha Cabcon & Insulation Limited": "GODHA",
    "Go Digit General Insurance Limited": "GODIGIT",
    "Godrej Consumer Products Limited": "GODREJCP",
    "Godrej Properties Limited": "GODREJPROP",
    "Godawari Power And Ispat limited": "GPIL",
    "Gujarat Pipavav Port Limited": "GPPL",
    "Granules India Limited": "GRANULES",
    "Graphite India Limited": "GRAPHITE",
    "Greaves Cotton Limited": "GREAVESCOT",
    "Orient Green Power Company Limited": "GREENPOWER",
    "Garden Reach Shipbuilders & Engineers Limited": "GRSE",
    "Gujarat State Fertilizers & Chemicals Limited": "GSFC",
    "GTL Limited": "GTL",
    "GTL Infrastructure Limited": "GTLINFRA",
    "Hindustan Aeronautics Limited": "HAL",
    "Hathway Cable & Datacom Limited": "HATHWAY",
    "Havells India Limited": "HAVELLS",
    "HBL Engineering Limited": "HBLENGINE",
    "HCL Technologies Limited": "HCLTECH",
    "HDB Financial Services Limited": "HDBFS",
    "HDFC Bank Limited": "HDFCBANK",
    "HDFC Life Insurance Company Limited": "HDFCLIFE",
    "HEG Limited": "HEG",
    "Hexaware Technologies Limited": "HEXT",
    "HFCL Limited": "HFCL",
    "Hindalco Industries Limited": "HINDALCO",
    "Hindustan Copper Limited": "HINDCOPPER",
    "Hindustan Petroleum Corporation Limited": "HINDPETRO",
    "Hindustan Unilever Limited": "HINDUNILVR",
    "Hindustan Zinc Limited": "HINDZINC",
    "Hi-Tech Pipes Limited": "HITECH",
    "HLV LIMITED": "HLVLTD",
    "Honasa Consumer Limited": "HONASA",
    "Himadri Speciality Chemical Limited": "HSCL",
    "Housing & Urban Development Corporation Limited": "HUDCO",
    "Hyundai Motor India Limited": "HYUNDAI",
    "ICICI Bank Limited": "ICICIBANK",
    "ICICI Prudential Life Insurance Company Limited": "ICICIPRULI",
    "IDBI Bank Limited": "IDBI",
    "Vodafone Idea Limited": "IDEA",
    "Ideaforge Technology Limited": "IDEAFORGE",
    "IDFC First Bank Limited": "IDFCFIRSTB",
    "Indian Energy Exchange Limited": "IEX",
    "IFCI Limited": "IFCI",
    "International Gemmological Institute (India) Limited": "IGIL",
    "Indraprastha Gas Limited": "IGL",
    "IIFL Finance Limited": "IIFL",
    "Indegene Limited": "INDGN",
    "The Indian Hotels Company Limited": "INDHOTEL",
    "Indian Bank": "INDIANB",
    "InterGlobe Aviation Limited": "INDIGO",
    "IndusInd Bank Limited": "INDUSINDBK",
    "Indus Towers Limited": "INDUSTOWER",
    "Infibeam Avenues Limited": "INFIBEAM",
    "Infosys Limited": "INFY",
    "Inox Wind Limited": "INOXWIND",
    "Inventure Growth & Securities Limited": "INVENTURE",
    "Indian Overseas Bank": "IOB",
    "Indian Oil Corporation Limited": "IOC",
    "IOL Chemicals and Pharmaceuticals Limited": "IOLCP",
    "IRB Infrastructure Developers Limited": "IRB",
    "Ircon International Limited": "IRCON",
    "Indian Railway Catering And Tourism Corporation Limited": "IRCTC",
    "Indian Renewable Energy Development Agency Limited": "IREDA",
    "Indian Railway Finance Corporation Limited": "IRFC",
    "ITC Limited": "ITC",
    "ITC Hotels Limited": "ITCHOTELS",
    "ITI Limited": "ITI",
    "Le Travenues Technology Limited": "IXIGO",
    "The Jammu & Kashmir Bank Limited": "J&KBANK",
    "Jai Balaji Industries Limited": "JAIBALAJI",
    "Jamna Auto Industries Limited": "JAMNAAUTO",
    "JBM Auto Limited": "JBMA",
    "Jindal Saw Limited": "JINDALSAW",
    "Jindal Steel & Power Limited": "JINDALSTEL",
    "Jindal Worldwide Limited": "JINDWORLD",
    "Jio Financial Services Limited": "JIOFIN",
    "Jain Irrigation Systems Limited": "JISLJALEQS",
    "JK Tyre & Industries Limited": "JKTYRE",
    "JM Financial Limited": "JMFINANCIL",
    "Jaiprakash Power Ventures Limited": "JPPOWER",
    "Jindal Stainless Limited": "JSL",
    "JSW Energy Limited": "JSWENERGY",
    "JSW Infrastructure Limited": "JSWINFRA",
    "JSW Steel Limited": "JSWSTEEL",
    "JTL INDUSTRIES LIMITED": "JTLIND",
    "Jubilant Foodworks Limited": "JUBLFOOD",
    "Jubilant Ingrevia Limited": "JUBLINGREA",
    "Jupiter Wagons Limited": "JWL",
    "Jyoti Structures Limited": "JYOTISTRUC",
    "Kalpataru Limited": "KALPATARU",
    "Kalyan Jewellers India Limited": "KALYANKJIL",
    "Kamdhenu Limited": "KAMDHENU",
    "Karur Vysya Bank Limited": "KARURVYSYA",
    "KEC International Limited": "KEC",
    "Kfin Technologies Limited": "KFINTECH",
    "KNR Constructions Limited": "KNRCON",
    "Kotak Mahindra Bank Limited": "KOTAKBANK",
    "KPI Green Energy Limited": "KPIGREEN",
    "KPIT Technologies Limited": "KPITTECH",
    "The Karnataka Bank Limited": "KTKBANK",
    "Laurus Labs Limited": "LAURUSLABS",
    "Lemon Tree Hotels Limited": "LEMONTREE",
    "LIC Housing Finance Limited": "LICHSGFIN",
    "Life Insurance Corporation Of India": "LICI",
    "LLOYDS ENGINEERING WORKS LIMITED": "LLOYDSENGG",
    "Lloyds Enterprises Limited": "LLOYDSENT",
    "Macrotech Developers Limited": "LODHA",
    "Larsen & Toubro Limited": "LT",
    "L&T Finance Limited": "LTF",
    "LT Foods Limited": "LTFOODS",
    "Lupin Limited": "LUPIN",
    "Mahindra & Mahindra Limited": "M&M",
    "Mahindra & Mahindra Financial Services Limited": "M&MFIN",
    "Bank of Maharashtra": "MAHABANK",
    "Manali Petrochemicals Limited": "MANALIPETC",
    "Manappuram Finance Limited": "MANAPPURAM",
    "Man Infraconstruction Limited": "MANINFRA",
    "Marico Limited": "MARICO",
    "Marksans Pharma Limited": "MARKSANS",
    "Max Healthcare Institute Limited": "MAXHEALTH",
    "Mazagon Dock Shipbuilders Limited": "MAZDOCK",
    "Max Financial Services Limited": "MFSL",
    "Mangalam Global Enterprise Limited": "MGEL",
    "MIC Electronics Limited": "MICEL",
    "Mishra Dhatu Nigam Limited": "MIDHANI",
    "Mittal Life Style Limited": "MITTAL",
    "MMTC Limited": "MMTC",
    "One Mobikwik Systems Limited": "MOBIKWIK",
    "MOIL Limited": "MOIL",
    "Meghmani Organics Limited": "MOL",
    "Morepen Laboratories Limited": "MOREPENLAB",
    "Moschip Technologies Limited": "MOSCHIP",
    "Samvardhana Motherson International Limited": "MOTHERSON",
    "Motilal Oswal Financial Services Limited": "MOTILALOFS",
    "Motisons Jewellers Limited": "MOTISONS",
    "Mangalore Refinery and Petrochemicals Limited": "MRPL",
    "Motherson Sumi Wiring India Limited": "MSUMI",
    "Mahanagar Telephone Nigam Limited": "MTNL",
    "Muthoot Finance Limited": "MUTHOOTFIN",
    "Nippon Life India Asset Management Limited": "NAM-INDIA",
    "Natco Pharma Limited": "NATCOPHARM",
    "National Aluminium Company Limited": "NATIONALUM",
    "Info Edge (India) Limited": "NAUKRI",
    "NAVA LIMITED": "NAVA",
    "NBCC (India) Limited": "NBCC",
    "NCC Limited": "NCC",
    "Nandan Denim Limited": "NDL",
    "Nectar Lifesciences Limited": "NECLIFE",
    "Network18 Media & Investments Limited": "NETWORK18",
    "Newgen Software Technologies Limited": "NEWGEN",
    "National Fertilizers Limited": "NFL",
    "NHPC Limited": "NHPC",
    "NIIT Limited": "NIITLTD",
    "Niva Bupa Health Insurance Company Limited": "NIVABUPA",
    "NLC India Limited": "NLCINDIA",
    "NMDC Limited": "NMDC",
    "Northern Arc Capital Limited": "NORTHARC",
    "NMDC Steel Limited": "NSLNISP",
    "NTPC Limited": "NTPC",
    "NTPC Green Energy Limited": "NTPCGREEN",
    "FSN E-Commerce Ventures Limited": "NYKAA",
    "Oil India Limited": "OIL",
    "Ola Electric Mobility Limited": "OLAELEC",
    "Oil & Natural Gas Corporation Limited": "ONGC",
    "Orient Cement Limited": "ORIENTCEM",
    "Orient Paper & Industries Limited": "ORIENTPPR",
    "Oswal Pumps Limited": "OSWALPUMPS",
    "Paisalo Digital Limited": "PAISALO",
    "Paramount Communications Limited": "PARACABLES",
    "Paradeep Phosphates Limited": "PARADEEP",
    "Parag Milk Foods Limited": "PARAGMILK",
    "Paras Defence and Space Technologies Limited": "PARAS",
    "Apeejay Surrendra Park Hotels Limited": "PARKHOTELS",
    "Parsvnath Developers Limited": "PARSVNATH",
    "Patel Engineering Limited": "PATELENG",
    "One 97 Communications Limited": "PAYTM",
    "PCBL Chemical Limited": "PCBL",
    "PC Jeweller Limited": "PCJEWELLER",
    "Petronet LNG Limited": "PETRONET",
    "Power Finance Corporation Limited": "PFC",
    "Prime Focus Limited": "PFOCUS",
    "PTC India Financial Services Limited": "PFS",
    "PG Electroplast Limited": "PGEL",
    "Punjab National Bank": "PNB",
    "PNB Housing Finance Limited": "PNBHOUSING",
    "PB Fintech Limited": "POLICYBZR",
    "Poonawalla Fincorp Limited": "POONAWALLA",
    "Power Grid Corporation of India Limited": "POWERGRID",
    "Piramal Pharma Limited": "PPLPHARMA",
    "Premier Explosives Limited": "PREMEXPLN",
    "Premier Energies Limited": "PREMIERENE",
    "Prostarm Info Systems Limited": "PROSTARM",
    "Punjab & Sind Bank": "PSB",
    "PTC India Limited": "PTC",
    "Quality Power Electrical Equipments Limited": "QPOWER",
    "Quadrant Future Tek Limited": "QUADFUTURE",
    "Railtel Corporation Of India Limited": "RAILTEL",
    "Rama Steel Tubes Limited": "RAMASTEEL",
    "Raymond Limited": "RAYMOND",
    "Restaurant Brands Asia Limited": "RBA",
    "RBL Bank Limited": "RBLBANK",
    "Rashtriya Chemicals and Fertilizers Limited": "RCF",
    "REC Limited": "RECLTD",
    "Redington Limited": "REDINGTON",
    "Reliance Industries Limited": "RELIANCE",
    "Shree Renuka Sugars Limited": "RENUKA",
    "RITES Limited": "RITES",
    "Ramkrishna Forgings Limited": "RKFORGE",
    "RattanIndia Enterprises Limited": "RTNINDIA",
    "RattanIndia Power Limited": "RTNPOWER",
    "Rail Vikas Nigam Limited": "RVNL",
    "Sagility India Limited": "SAGILITY",
    "Steel Authority of India Limited": "SAIL",
    "Salasar Techno Engineering Limited": "SALASAR",
    "Sambhv Steel Tubes Limited": "SAMBHV",
    "Samhi Hotels Limited": "SAMHI",
    "Sammaan Capital Limited": "SAMMAANCAP",
    "Sarda Energy & Minerals Limited": "SARDAEN",
    "Sarveshwar Foods Limited": "SARVESHWAR",
    "SBC Exports Limited": "SBC",
    "SBFC Finance Limited": "SBFC",
    "SBI Cards and Payment Services Limited": "SBICARD",
    "SBI Life Insurance Company Limited": "SBILIFE",
    "State Bank of India": "SBIN",
    "Shipping Corporation Of India Limited": "SCI",
    "Shipping Corporation of India Land and Assets Limited": "SCILAL",
    "Scoda Tubes Limited": "SCODATUBES",
    "Som Distilleries & Breweries Limited": "SDBL",
    "SEPC Limited": "SEPC",
    "Servotech Renewable Power System Limited": "SERVOTECH",
    "Shriram Finance Limited": "SHRIRAMFIN",
    "Shriram Properties Limited": "SHRIRAMPPS",
    "Sigachi Industries Limited": "SIGACHI",
    "Sindhu Trade Links Limited": "SINDHUTRAD",
    "SJVN Limited": "SJVN",
    "SKY GOLD AND DIAMONDS LIMITED": "SKYGOLD",
    "Sona BLW Precision Forgings Limited": "SONACOMS",
    "Sonata Software Limited": "SONATSOFTW",
    "The South Indian Bank Limited": "SOUTHBANK",
    "Sun Pharma Advanced Research Company Limited": "SPARC",
    "Star Health and Allied Insurance Company Limited": "STARHEALTH",
    "STEEL EXCHANGE INDIA LIMITED": "STEELXIND",
    "Sterlite Technologies Limited": "STLTECH",
    "Sun Pharmaceutical Industries Limited": "SUNPHARMA",
    "Suzlon Energy Limited": "SUZLON",
    "Swan Energy Limited": "SWANENERGY",
    "Swiggy Limited": "SWIGGY",
    "Sterling and Wilson Renewable Energy Limited": "SWSOLAR",
    "Syngene International Limited": "SYNGENE",
    "Syrma SGS Technology Limited": "SYRMA",
    "Tanla Platforms Limited": "TANLA",
    "Transformers And Rectifiers (India) Limited": "TARIL",
    "TATA CONSUMER PRODUCTS LIMITED": "TATACONSUM",
    "Tata Motors Limited": "TATAMOTORS",
    "Tata Power Company Limited": "TATAPOWER",
    "Tata Steel Limited": "TATASTEEL",
    "Tata Technologies Limited": "TATATECH",
    "Tata Consultancy Services Limited": "TCS",
    "TD Power Systems Limited": "TDPOWERSYS",
    "Tech Mahindra Limited": "TECHM",
    "Tejas Networks Limited": "TEJASNET",
    "Texmaco Rail & Engineering Limited": "TEXRAIL",
    "Tourism Finance Corporation of India Limited": "TFCILTD",
    "Schloss Bangalore Limited": "THELEELA",
    "Thomas Cook  (India)  Limited": "THOMASCOOK",
    "Tilaknagar Industries Limited": "TI",
    "Time Technoplast Limited": "TIMETECHNO",
    "TITAGARH RAIL SYSTEMS LIMITED": "TITAGARH",
    "Transrail Lighting Limited": "TRANSRAILL",
    "Trent Limited": "TRENT",
    "Trident Limited": "TRIDENT",
    "Triveni Turbine Limited": "TRITURBINE",
    "UCO Bank": "UCOBANK",
    "Ujjivan Small Finance Bank Limited": "UJJIVANSFB",
    "Union Bank of India": "UNIONBANK",
    "United Spirits Limited": "UNITDSPR",
    "UPL Limited": "UPL",
    "Urja Global Limited": "URJA",
    "Utkarsh Small Finance Bank Limited": "UTKARSHBNK",
    "Vascon Engineers Limited": "VASCONEQ",
    "Varun Beverages Limited": "VBL",
    "Vedanta Limited": "VEDL",
    "Vikas EcoTech Limited": "VIKASECO",
    "Vikas Lifecare Limited": "VIKASLIFE",
    "Vintage Coffee And Beverages Limited": "VINCOFE",
    "Vishal Mega Mart Limited": "VMM",
    "Voltas Limited": "VOLTAS",
    "Waaree Energies Limited": "WAAREEENER",
    "Welspun Corp Limited": "WELCORP",
    "Welspun Living Limited": "WELSPUNLIV",
    "Wipro Limited": "WIPRO",
    "Yes Bank Limited": "YESBANK",
    "Zee Entertainment Enterprises Limited": "ZEEL",
    "Zee Media Corporation Limited": "ZEEMEDIA",
    "Zensar Technologies Limited": "ZENSARTECH",
    "Zydus Lifesciences Limited": "ZYDUSLIFE"
}
