STOCKS = {'20 Microns Limited':'20MICRONS',
'21st Century Management Services Limited':'21STCENMGM',
'360 ONE WAM LIMITED':'360ONE',
'3i Infotech Limited':'3IINFOLTD',
'3M India Limited':'3MINDIA',
'3P Land Holdings Limited':'3PLAND',
'5Paisa Capital Limited':'5PAISA',
'63 moons technologies limited':'63MOONS',
'AAA Technologies Limited':'AAATECH',
'Aadhar Housing Finance Limited':'AADHARHFC',
'Aaron Industries Limited':'AARON',
'Aartech Solonics Limited':'AARTECH',
'Aarti Drugs Limited':'AARTIDRUGS',
'Aarti Industries Limited':'AARTIIND',
'Aarti Pharmalabs Limited':'AARTIPHARM',
'Aarvi Encon Limited':'AARVI',
'Aavas Financiers Limited':'AAVAS',
'Aban Offshore Limited':'ABAN',
'ABB India Limited':'ABB',
'Abbott India Limited':'ABBOTINDIA',
'Aditya Birla Capital Limited':'ABCAPITAL',
'Allied Blenders and Distillers Limited':'ABDL',
'Aditya Birla Fashion and Retail Limited':'ABFRL',
'Aditya Birla Real Estate Limited':'ABREL',
'Aditya Birla Sun Life AMC Limited':'ABSLAMC',
'ACC Limited':'ACC',
'Accelya Solutions India Limited':'ACCELYA',
'Accuracy Shipping Limited':'ACCURACY',
'Action Construction Equipment Limited':'ACE',
'Ace Integrated Solutions Limited':'ACEINTEG',
'Archean Chemical Industries Limited':'ACI',
'Andhra Cements Limited':'ACL',
'Allcargo Gati Limited':'ACLGATI',
'Acme Solar Holdings Limited':'ACMESOLAR',
'Acutaas Chemicals Limited':'ACUTAAS',
'Adani Energy Solutions Limited':'ADANIENSOL',
'Adani Enterprises Limited':'ADANIENT',
'Adani Green Energy Limited':'ADANIGREEN',
'Adani Ports and Special Economic Zone Limited':'ADANIPORTS',
'Adani Power Limited':'ADANIPOWER',
'ADF Foods Limited':'ADFFOODS',
'Ador Welding Limited':'ADOR',
'Adroit Infotech Limited':'ADROITINFO',
'Allied Digital Services Limited':'ADSL',
'Advani Hotels & Resorts (India) Limited':'ADVANIHOTR',
'Advanced Enzyme Technologies Limited':'ADVENZYMES',
'Aegis Logistics Limited':'AEGISLOG',
'Aegis Vopak Terminals Limited':'AEGISVOPAK',
'Aeroflex Enterprises Limited':'AEROENTER',
'Aeroflex Industries Limited':'AEROFLEX',
'Aether Industries Limited':'AETHER',
'Afcons Infrastructure Limited':'AFCONS',
'Affle 3i Limited':'AFFLE',
'Affordable Robotic & Automation Limited':'AFFORDABLE',
'Akme Fintrade (India) Limited':'AFIL',
'Abans Financial Services Limited':'AFSL',
'Agarwal Industrial Corporation Limited':'AGARIND',
'AGI Greenpac Limited':'AGI',
'Agi Infra Limited':'AGIIL',
'Agri-Tech (India) Limited':'AGRITECH',
'Agro Phos India Limited':'AGROPHOS',
'Ahlada Engineers Limited':'AHLADA',
'Asian Hotels (East) Limited':'AHLEAST',
'Ahluwalia Contracts (India) Limited':'AHLUCONT',
'AIA Engineering Limited':'AIAENG',
'Authum Investment & Infrastructure Limited':'AIIL',
'Airan Limited':'AIRAN',
'Airo Lam limited':'AIROLAM',
'Ajanta Pharma Limited':'AJANTPHARM',
'Ajax Engineering Limited':'AJAXENGG',
'Ajmera Realty & Infra India Limited':'AJMERA',
'Ajooni Biotech Limited':'AJOONI',
'Akash Infra-Projects Limited':'AKASH',
'Akg Exim Limited':'AKG',
'AksharChem India Limited':'AKSHARCHEM',
'Aksh Optifibre Limited':'AKSHOPTFBR',
'Akums Drugs and Pharmaceuticals Limited':'AKUMS',
'Akzo Nobel India Limited':'AKZOINDIA',
'Alankit Limited':'ALANKIT',
'Albert David Limited':'ALBERTDAVD',
'Alembic Limited':'ALEMBICLTD',
'Alicon Castalloy Limited':'ALICON',
'Alivus Life Sciences Limited':'ALIVUS',
'Alkali Metals Limited':'ALKALI',
'Alkem Laboratories Limited':'ALKEM',
'Alkyl Amines Chemicals Limited':'ALKYLAMINE',
'Allcargo Logistics Limited':'ALLCARGO',
'Alldigi Tech Limited':'ALLDIGI',
'Almondz Global Securities Limited':'ALMONDZ',
'Alok Industries Limited':'ALOKINDS',
'Alpa Laboratories Limited':'ALPA',
'Alphageo (India) Limited':'ALPHAGEO',
'Amber Enterprises India Limited':'AMBER',
'Ambica Agarbathies & Aroma industries Limited':'AMBICAAGAR',
'Ambika Cotton Mills Limited':'AMBIKCO',
'Ambuja Cements Limited':'AMBUJACEM',
'AMD Industries Limited':'AMDIND',
'Amj Land Holdings Limited':'AMJLAND',
'Amines & Plasticizers Limited':'AMNPLST',
'Amrutanjan Health Care Limited':'AMRUTANJAN',
'Anand Rathi Wealth Limited':'ANANDRATHI',
'Anant Raj Limited':'ANANTRAJ',
'ANDHRA PAPER LIMITED':'ANDHRAPAP',
'The Andhra Sugars Limited':'ANDHRSUGAR',
'Angel One Limited':'ANGELONE',
'Anik Industries Limited':'ANIKINDS',
'Anmol India Limited':'ANMOL',
'Antarctica Limited':'ANTGRAPHIC',
'Anuh Pharma Limited':'ANUHPHR',
'The Anup Engineering Limited':'ANUP',
'Anupam Rasayan India Limited':'ANURAS',
'Apar Industries Limited':'APARINDS',
'Apcotex Industries Limited':'APCOTEXIND',
'Apex Frozen Foods Limited':'APEX',
'APL Apollo Tubes Limited':'APLAPOLLO',
'Alembic Pharmaceuticals Limited':'APLLTD',
'Apollo Micro Systems Limited':'APOLLO',
'Apollo Hospitals Enterprise Limited':'APOLLOHOSP',
'Apollo Pipes Limited':'APOLLOPIPE',
'Apollo Tyres Limited':'APOLLOTYRE',
'Apollo Sindoori Hotels Limited':'APOLSINHOT',
'Aptus Value Housing Finance India Limited':'APTUS',
'Archidply Industries Limited':'ARCHIDPLY',
'Amara Raja Energy & Mobility Limited':'ARE&M',
'Rajdarshan Industries Limited':'ARENTERP',
'Aries Agro Limited':'ARIES',
'Arihant Capital Markets Limited':'ARIHANTCAP',
'Arihant Superstructures Limited':'ARIHANTSUP',
'Arisinfra Solutions Limited':'ARISINFRA',
'Arkade Developers Limited':'ARKADE',
'Arman Financial Services Limited':'ARMANFIN',
'Aro Granite Industries Limited':'AROGRANITE',
'Artemis Medicare Services Limited':'ARTEMISMED',
'Arvee Laboratories (India) Limited':'ARVEE',
'Arvind Limited':'ARVIND',
'Arvind Fashions Limited':'ARVINDFASN',
'Arvind SmartSpaces Limited':'ARVSMART',
'Asahi India Glass Limited':'ASAHIINDIA',
'Automotive Stampings and Assemblies Limited':'ASAL',
'Associated Alcohols & Breweries Ltd.':'ASALCBR',
'Ashapura Minechem Limited':'ASHAPURMIN',
'Ashiana Housing Limited':'ASHIANA',
'Ashoka Buildcon Limited':'ASHOKA',
'Ashoka Metcast Limited':'ASHOKAMET',
'Ashok Leyland Limited':'ASHOKLEY',
'Asian Energy Services Limited':'ASIANENE',
'Asian Paints Limited':'ASIANPAINT',
'ASK Automotive Limited':'ASKAUTOLTD',
'Bartronics India Limited':'ASMS',
'Aspinwall and Company Limited':'ASPINWALL',
'Astec LifeSciences Limited':'ASTEC',
'Aster DM Healthcare Limited':'ASTERDM',
'Astral Limited':'ASTRAL',
'Astra Microwave Products Limited':'ASTRAMICRO',
'AstraZeneca Pharma India Limited':'ASTRAZEN',
'Atam Valves Limited':'ATAM',
'Adani Total Gas Limited':'ATGL',
'Ather Energy Limited':'ATHERENERG',
'Allcargo Terminals Limited':'ATL',
'ATLANTAA LIMITED':'ATLANTAA',
'Atul Limited':'ATUL',
'Atul Auto Limited':'ATULAUTO',
'AU Small Finance Bank Limited':'AUBANK',
'Aurionpro Solutions Limited':'AURIONPRO',
'Aurobindo Pharma Limited':'AUROPHARMA',
'Aurum PropTech Limited':'AURUM',
'Automotive Axles Limited':'AUTOAXLES',
'Autoline Industries Limited':'AUTOIND',
'Avadh Sugar & Energy Limited':'AVADHSUGAR',
'Avalon Technologies Limited':'AVALON',
'Avantel Limited':'AVANTEL',
'Avanti Feeds Limited':'AVANTIFEED',
'AVG Logistics Limited':'AVG',
'Aditya Vision Limited':'AVL',
'AVRO INDIA LIMITED':'AVROIND',
'AVT Natural Products Limited':'AVTNPL',
'Awfis Space Solutions Limited':'AWFIS',
'Antony Waste Handling Cell Limited':'AWHCL',
'AWL Agri Business Limited':'AWL',
'Axis Bank Limited':'AXISBANK',
'Axita Cotton Limited':'AXITA',
'AYM Syntex Limited':'AYMSYNTEX',
'Azad Engineering Limited':'AZAD',
'Bafna Pharmaceuticals Limited':'BAFNAPH',
'B.A.G Films and Media Limited':'BAGFILMS',
'Baid Finserv Limited':'BAIDFIN',
'Bajaj Auto Limited':'BAJAJ-AUTO',
'Bajaj Consumer Care Limited':'BAJAJCON',
'Bajaj Electricals Limited':'BAJAJELEC',
'Bajaj Finserv Limited':'BAJAJFINSV',
'Bajaj Healthcare Limited':'BAJAJHCARE',
'Bajaj Housing Finance Limited':'BAJAJHFL',
'Bajaj Hindusthan Sugar Limited':'BAJAJHIND',
'Bajaj Holdings & Investment Limited':'BAJAJHLDNG',
'Indef Manufacturing Limited':'BAJAJINDEF',
'Bajaj Finance Limited':'BAJFINANCE',
'Shree Tirupati Balajee Agro Trading Company Limited':'BALAJEE',
'Balaji Amines Limited':'BALAMINES',
'BALAXI PHARMACEUTICALS LIMITED':'BALAXI',
'Balkrishna Paper Mills Limited':'BALKRISHNA',
'Balkrishna Industries Limited':'BALKRISIND',
'Balmer Lawrie & Company Limited':'BALMLAWRIE',
'Bal Pharma Limited':'BALPHARMA',
'Balrampur Chini Mills Limited':'BALRAMCHIN',
'Banaras Beads Limited':'BANARBEADS',
'Bannari Amman Sugars Limited':'BANARISUG',
'Banco Products (I) Limited':'BANCOINDIA',
'Bandhan Bank Limited':'BANDHANBNK',
'Bang Overseas Limited':'BANG',
'Banka BioLoo Limited':'BANKA',
'Bank of Baroda':'BANKBARODA',
'Bank of India':'BANKINDIA',
'Bansal Wire Industries Limited':'BANSALWIRE',
'Banswara Syntex Limited':'BANSWRAS',
'Barbeque Nation Hospitality Limited':'BARBEQUE',
'BASF India Limited':'BASF',
'Bannari Amman Spinning Mills Limited':'BASML',
'Bata India Limited':'BATAINDIA',
'Bayer Cropscience Limited':'BAYERCROP',
'Bharat Bijlee Limited':'BBL',
'Bombay Burmah Trading Corporation Limited':'BBTC',
'B&B Triplewall Containers Limited':'BBTCL',
'Bcl Industries Limited':'BCLIND',
'Brand Concepts Limited':'BCONCEPTS',
'Bharat Dynamics Limited':'BDL',
'Beardsell Limited':'BEARDSELL',
'Mrs. Bectors Food Specialities Limited':'BECTORFOOD',
'Bedmutha Industries Limited':'BEDMUTHA',
'Bharat Electronics Limited':'BEL',
'Belrise Industries Limited':'BELRISE',
'BEML Limited':'BEML',
'Bhansali Engineering Polymers Limited':'BEPL',
'Berger Paints (I) Limited':'BERGEPAINT',
'Best Agrolife Limited':'BESTAGRO',
'BF Investment Limited':'BFINVEST',
'BF Utilities Limited':'BFUTILITIE',
'Bhagiradha Chemicals & Industries Limited':'BHAGCHEM',
'Bhageria Industries Limited':'BHAGERIA',
'Bhagyanagar India Limited':'BHAGYANGR',
'Bhandari Hosiery Exports Limited':'BHANDARI',
'Bharat Forge Limited':'BHARATFORG',
'Bharat Gears Limited':'BHARATGEAR',
'Bharat Rasayan Limited':'BHARATRAS',
'Bharat Wire Ropes Limited':'BHARATWIRE',
'Bharti Airtel Limited':'BHARTIARTL',
'Bharti Hexacom Limited':'BHARTIHEXA',
'Bharat Heavy Electricals Limited':'BHEL',
'Bigbloc Construction Limited':'BIGBLOC',
'Bikaji Foods International Limited':'BIKAJI',
'Bhartiya International Limited':'BIL',
'Biocon Limited':'BIOCON',
'Birla Corporation Limited':'BIRLACORPN',
'Aditya Birla Money Limited':'BIRLAMONEY',
'BirlaNu Limited':'BIRLANU',
'Zinka Logistics Solutions Limited':'BLACKBUCK',
'BEML Land Assets Limited':'BLAL',
'BLB Limited':'BLBLIMITED',
'Bliss GVS Pharma Limited':'BLISSGVS',
'B. L. Kashyap and Sons Limited':'BLKASHYAP',
'BLS International Services Limited':'BLS',
'Blue Dart Express Limited':'BLUEDART',
'Blue Jet Healthcare Limited':'BLUEJET',
'Blue Star Limited':'BLUESTARCO',
'Bluspring Enterprises Limited':'BLUSPRING',
'Bodal Chemicals Limited':'BODALCHEM',
'Bombay Dyeing & Mfg Company Limited':'BOMDYEING',
'Borana Weaves Limited':'BORANA',
'Borosil Limited':'BOROLTD',
'BOROSIL RENEWABLES LIMITED':'BORORENEW',
'Borosil Scientific Limited':'BOROSCI',
'Bosch Limited':'BOSCHLTD',
'Bharat Petroleum Corporation Limited':'BPCL',
'BPL Limited':'BPL',
'Brigade Enterprises Limited':'BRIGADE',
'Britannia Industries Limited':'BRITANNIA',
'BSE Limited':'BSE',
'Bombay Super Hybrid Seeds Limited':'BSHSL',
'BIRLASOFT LIMITED':'BSOFT',
'Bodhi Tree Multimedia Limited':'BTML',
'Butterfly Gandhimathi Appliances Limited':'BUTTERFLY',
'Barak Valley Cements Limited':'BVCL',
'Campus Activewear Limited':'CAMPUS',
'Computer Age Management Services Limited':'CAMS',
'Canara Bank':'CANBK',
'Can Fin Homes Limited':'CANFINHOME',
'Cantabil Retail India Limited':'CANTABIL',
'Capital Small Finance Bank Limited':'CAPITALSFB',
'Caplin Point Laboratories Limited':'CAPLIPOINT',
'Carborundum Universal Limited':'CARBORUNIV',
'CARE Ratings Limited':'CARERATING',
'Carraro India Limited':'CARRARO',
'Cartrade Tech Limited':'CARTRADE',
'CARYSIL LIMITED':'CARYSIL',
'Castrol India Limited':'CASTROLIND',
'Consolidated Construction Consortium Limited':'CCCL',
'Country Club Hospitality & Holidays Limited':'CCHHL',
'CCL Products (India) Limited':'CCL',
'Central Depository Services (India) Limited':'CDSL',
'CEAT Limited':'CEATLTD',
'Ceigall India Limited':'CEIGALL',
'Celebrity Fashions Limited':'CELEBRITY',
'Cello World Limited':'CELLO',
'Century Enka Limited':'CENTENKA',
'Century Extrusions Limited':'CENTEXT',
'Central Bank of India':'CENTRALBK',
'Centum Electronics Limited':'CENTUM',
'Century Plyboards (India) Limited':'CENTURYPLY',
'Cera Sanitaryware Limited':'CERA',
'CESC Limited':'CESC',
'Concord Enviro Systems Limited':'CEWATER',
'Capri Global Capital Limited':'CGCL',
'CG Power and Industrial Solutions Limited':'CGPOWER',
'Chalet Hotels Limited':'CHALET',
'Chambal Fertilizers & Chemicals Limited':'CHAMBLFERT',
'Chemcon Speciality Chemicals Limited':'CHEMCON',
'Chemfab Alkalis Limited':'CHEMFAB',
'Chemplast Sanmar Limited':'CHEMPLASTS',
'Chennai Petroleum Corporation Limited':'CHENNPETRO',
'Cheviot Company Limited':'CHEVIOT',
'Choice International Limited':'CHOICEIN',
'Cholamandalam Investment and Finance Company Limited':'CHOLAFIN',
'Cholamandalam Financial Holdings Limited':'CHOLAHLDNG',
'CIE Automotive India Limited':'CIEINDIA',
'Capital India Finance Limited':'CIFL',
'Cigniti Technologies Limited':'CIGNITITEC',
'Cineline India Limited':'CINELINE',
'Cipla Limited':'CIPLA',
'Clean Science and Technology Limited':'CLEAN',
'CL Educate Limited':'CLEDUCATE',
'Chaman Lal Setia Exports Limited':'CLSEL',
'CMS Info Systems Limited':'CMSINFO',
'Coal India Limited':'COALINDIA',
'Coastal Corporation Limited':'COASTCORP',
'Cochin Shipyard Limited':'COCHINSHIP',
'Coffee Day Enterprises Limited':'COFFEEDAY',
'Coforge Limited':'COFORGE',
'Cohance Lifesciences Limited':'COHANCE',
'Colgate Palmolive (India) Limited':'COLPAL',
'Compucom Software Limited':'COMPUSOFT',
'Commercial Syn Bags Limited':'COMSYN',
'Container Corporation of India Limited':'CONCOR',
'Concord Biotech Limited':'CONCORDBIO',
'Confidence Petroleum India Limited':'CONFIPET',
'Consolidated Finvest & Holdings Limited':'CONSOFINVT',
'Control Print Limited':'CONTROLPR',
'Coral India Finance & Housing Limited':'CORALFINAC',
'Cords Cable Industries Limited':'CORDSCABLE',
'Coromandel International Limited':'COROMANDEL',
'COSMO FIRST LIMITED':'COSMOFIRST',
'CP Capital Limited':'CPCAP',
'Craftsman Automation Limited':'CRAFTSMAN',
'Creative Newtech Limited':'CREATIVE',
'CREDITACCESS GRAMEEN LIMITED':'CREDITACC',
'Crest Ventures Limited':'CREST',
'CRISIL Limited':'CRISIL',
'Crompton Greaves Consumer Electricals Limited':'CROMPTON',
'Crown Lifters Limited':'CROWN',
'CSB Bank Limited':'CSBBANK',
'CSL Finance Limited':'CSLFINANCE',
'City Union Bank Limited':'CUB',
'Cubex Tubings Limited':'CUBEXTUB',
'Cummins India Limited':'CUMMINSIND',
'Cupid Limited':'CUPID',
'Cyber Media (India) Limited':'CYBERMEDIA',
'Cyient Limited':'CYIENT',
'Cyient DLM Limited':'CYIENTDLM',
'Dabur India Limited':'DABUR',
'Dalmia Bharat Limited':'DALBHARAT',
'Dalmia Bharat Sugar and Industries Limited':'DALMIASUG',
'Dam Capital Advisors Limited':'DAMCAPITAL',
'Damodar Industries Limited':'DAMODARIND',
'Dangee Dums Limited':'DANGEE',
'Datamatics Global Services Limited':'DATAMATICS',
'Data Patterns (India) Limited':'DATAPATTNS',
'Davangere Sugar Company Limited':'DAVANGERE',
'D.B.Corp Limited':'DBCORP',
'Deepak Builders & Engineers India Limited':'DBEIL',
'Dilip Buildcon Limited':'DBL',
'Valor Estate Limited':'DBREALTY',
'DB (International) Stock Brokers Limited':'DBSTOCKBRO',
'DCB Bank Limited':'DCBBANK',
'Dc Infotech And Communication Limited':'DCI',
'DCM  Limited':'DCM',
'DCM Nouvelle Limited':'DCMNVL',
'DCM Shriram Limited':'DCMSHRIRAM',
'DCM Shriram Industries Limited':'DCMSRIND',
'DCW Limited':'DCW',
'DCX Systems Limited':'DCXINDIA',
'Ddev Plastiks Industries Limited':'DDEVPLSTIK',
'Deccan Cements Limited':'DECCANCE',
'DEE Development Engineers Limited':'DEEDEV',
'Deepak Fertilizers and Petrochemicals Corporation Limited':'DEEPAKFERT',
'Deepak Nitrite Limited':'DEEPAKNTR',
'Deep Industries Limited':'DEEPINDS',
'Delhivery Limited':'DELHIVERY',
'DELPHI WORLD MONEY LIMITED':'DELPHIFX',
'Delta Corp Limited':'DELTACORP',
'Den Networks Limited':'DEN',
'De Nora India Limited':'DENORA',
'Denta Water and Infra Solutions Limited':'DENTA',
'Dev Information Technology Limited':'DEVIT',
'Devyani International Limited':'DEVYANI',
'Digicontent Limited':'DGCONTENT',
'Dhampur Sugar Mills Limited':'DHAMPURSUG',
'Dhanlaxmi Bank Limited':'DHANBANK',
'Dhani Services Limited':'DHANI',
'Dhanuka Agritech Limited':'DHANUKA',
'Dhunseri Investments Limited':'DHUNINV',
'Diamond Power Infrastructure Limited':'DIACABS',
'Diamines & Chemicals Limited':'DIAMINESQ',
'Prataap Snacks Limited':'DIAMONDYD',
'DIC India Limited':'DICIND',
'Diffusion Engineers Limited':'DIFFNKG',
'Digidrive Distributors Limited':'DIGIDRIVE',
'DiGiSPICE Technologies Limited':'DIGISPICE',
'Digitide Solutions Limited':'DIGITIDE',
'Divgi Torqtransfer Systems Limited':'DIVGIITTS',
'Divis Laboratories Limited':'DIVISLAB',
'Dixon Technologies (India) Limited':'DIXON',
'DJ Mediaprint & Logistics Limited':'DJML',
'DLF Limited':'DLF',
'D-Link (India) Limited':'DLINKINDIA',
'Avenue Supermarts Limited':'DMART',
'DMCC SPECIALITY CHEMICALS LIMITED':'DMCC',
'Diligent Media Corporation Limited':'DNAMEDIA',
'Dodla Dairy Limited':'DODLA',
'Dolat Algotech Limited':'DOLATALGO',
'Dollar Industries Limited':'DOLLAR',
'Dolphin Offshore Enterprises (India) Limited':'DOLPHIN',
'DOMS Industries Limited':'DOMS',
'Donear Industries Limited':'DONEAR',
'D. P. Abhushan Limited':'DPABHUSHAN',
'DPSC Limited':'DPSCLTD',
'D P Wires Limited':'DPWIRES',
'Dreamfolks Services Limited':'DREAMFOLKS',
'Dredging Corporation of India Limited':'DREDGECORP',
'Dr. Reddys Laboratories Limited':'DRREDDY',
'Dynacons Systems & Solutions Limited':'DSSL',
'Dhunseri Tea & Industries Limited':'DTIL',
'Ducon Infratechnologies Limited':'DUCON',
'Dhunseri Ventures Limited':'DVL',
'Dwarikesh Sugar Industries Limited':'DWARKESH',
'Dynamic Cables Limited':'DYCL',
'Dynamatic Technologies Limited':'DYNAMATECH',
'Dynemic Products Limited':'DYNPRO',
'E2E Networks Limited':'E2E',
'Easy Trip Planners Limited':'EASEMYTRIP',
'eClerx Services Limited':'ECLERX',
'Ecos (India) Mobility & Hospitality Limited':'ECOSMOBLTY',
'Edelweiss Financial Services Limited':'EDELWEISS',
'Eicher Motors Limited':'EICHERMOT',
'EID Parry India Limited':'EIDPARRY',
'Enviro Infra Engineers Limited':'EIEL',
'Euro India Fresh Foods Limited':'EIFFL',
'EIH Associated Hotels Limited':'EIHAHOTELS',
'EIH Limited':'EIHOTEL',
'Eimco Elecon (India) Limited':'EIMCOELECO',
'Everest Kanto Cylinder Limited':'EKC',
'Eldeco Housing And Industries Limited':'ELDEHSG',
'Elecon Engineering Company Limited':'ELECON',
'Electrosteel Castings Limited':'ELECTCAST',
'Electrotherm (India) Limited':'ELECTHERM',
'Elgi Equipments Limited':'ELGIEQUIP',
'Ellenbarrie Industrial Gases Limited':'ELLEN',
'Emami Limited':'EMAMILTD',
'Emami Paper Mills Limited':'EMAMIPAP',
'Embassy Developments Limited':'EMBDL',
'Emcure Pharmaceuticals Limited':'EMCURE',
'Electronics Mart India Limited':'EMIL',
'Emmbi Industries Limited':'EMMBI',
'EMS Limited':'EMSLIMITED',
'eMudhra Limited':'EMUDHRA',
'Endurance Technologies Limited':'ENDURANCE',
'Engineers India Limited':'ENGINERSIN',
'Entertainment Network (India) Limited':'ENIL',
'Siemens Energy India Limited':'ENRIN',
'Entero Healthcare Solutions Limited':'ENTERO',
'EPACK Durable Limited':'EPACK',
'Epigral Limited':'EPIGRAL',
'EPL Limited':'EPL',
'Equitas Small Finance Bank Limited':'EQUITASBNK',
'Eris Lifesciences Limited':'ERIS',
'Esab India Limited':'ESABINDIA',
'ESAF Small Finance Bank Limited':'ESAFSFB',
'Escorts Kubota Limited':'ESCORTS',
'Integra Essentia Limited':'ESSENTIA',
'Ester Industries Limited':'ESTER',
'ETERNAL LIMITED':'ETERNAL',
'Ethos Limited':'ETHOSLTD',
'Eureka Forbes Limited':'EUREKAFORB',
'Eurotex Industries and Exports Limited':'EUROTEXIND',
'Eveready Industries India Limited':'EVEREADY',
'Excel Realty N Infra Limited':'EXCEL',
'Excel Industries Limited':'EXCELINDUS',
'Exicom Tele-Systems Limited':'EXICOM',
'Exide Industries Limited':'EXIDEIND',
'Expleo Solutions Limited':'EXPLEOSOL',
'Fertilizers and Chemicals Travancore Limited':'FACT',
'Fairchem Organics Limited':'FAIRCHEMOR',
'Faze Three Limited':'FAZE3Q',
'Fineotex Chemical Limited':'FCL',
'FCS Software Solutions Limited':'FCSSOFT',
'FDC Limited':'FDC',
'The Federal Bank  Limited':'FEDERALBNK',
'Fedbank Financial Services Limited':'FEDFINA',
'Fiberweb (India) Limited':'FIBERWEB',
'Fiem Industries Limited':'FIEMIND',
'Filatex India Limited':'FILATEX',
'Filatex Fashions Limited':'FILATFASH',
'Finolex Cables Limited':'FINCABLES',
'Fine Organic Industries Limited':'FINEORG',
'Fino Payments Bank Limited':'FINOPB',
'Finolex Industries Limited':'FINPIPE',
'Brainbees Solutions Limited':'FIRSTCRY',
'Five-Star Business Finance Limited':'FIVESTAR',
'Flair Writing Industries Limited':'FLAIR',
'Gujarat Fluorochemicals Limited':'FLUOROCHEM',
'Federal-Mogul Goetze (India) Limited.':'FMGOETZE',
'FORCE MOTORS LTD':'FORCEMOT',
'Fortis Healthcare Limited':'FORTIS',
'Foseco India Limited':'FOSECOIND',
'Firstsource Solutions Limited':'FSL',
'Fusion Finance Limited':'FUSION',
'Gabriel India Limited':'GABRIEL',
'Gujarat Ambuja Exports Limited':'GAEL',
'GAIL (India) Limited':'GAIL',
'Gala Precision Engineering Limited':'GALAPREC',
'Galaxy Surfactants Limited':'GALAXYSURF',
'Gallantt Ispat Limited':'GALLANTT',
'Gandhar Oil Refinery (India) Limited':'GANDHAR',
'Gandhi Special Tubes Limited':'GANDHITUBE',
'Ganesha Ecosphere Limited':'GANECOS',
'Ganesh Benzoplast Limited':'GANESHBE',
'Ganesh Housing Corporation Limited':'GANESHHOUC',
'Ganga Forging Limited':'GANGAFORGE',
'Ganges Securities Limited':'GANGESSECU',
'Garware Technical Fibres Limited':'GARFIBRES',
'Garuda Construction and Engineering Limited':'GARUDA',
'GACM Technologies Limited':'GATECHDVR',
'Gateway Distriparks Limited':'GATEWAY',
'GeeCee Ventures Limited':'GEECEE',
'Geekay Wires Limited':'GEEKAYWIRE',
'Genesys International Corporation Limited':'GENESYS',
'Genus Paper & Boards Limited':'GENUSPAPER',
'Genus Power Infrastructures Limited':'GENUSPOWER',
'Geojit Financial Services Limited':'GEOJITFSL',
'GE Power India Limited':'GEPIL',
'The Great Eastern Shipping Company Limited':'GESHIP',
'GFL Limited':'GFLLIMITED',
'GHCL Limited':'GHCL',
'GHCL Textiles Limited':'GHCLTEXTIL',
'GIC Housing Finance Limited':'GICHSGFIN',
'General Insurance Corporation of India':'GICRE',
'Gillanders Arbuthnot & Company Limited':'GILLANDERS',
'Gillette India Limited':'GILLETTE',
'Gujarat Industries Power Company Limited':'GIPCL',
'GKW Limited':'GKWLIMITED',
'Gland Pharma Limited':'GLAND',
'GlaxoSmithKline Pharmaceuticals Limited':'GLAXO',
'Glenmark Pharmaceuticals Limited':'GLENMARK',
'Global Vectra Helicorp Limited':'GLOBALVECT',
'Globe Textiles (India) Limited':'GLOBE',
'Globus Spirits Limited':'GLOBUSSPR',
'Gloster Limited':'GLOSTERLTD',
'GM Breweries Limited':'GMBREW',
'Gujarat Mineral Development Corporation Limited':'GMDCLTD',
'GMM Pfaudler Limited':'GMMPFAUDLR',
'GMR AIRPORTS LIMITED':'GMRAIRPORT',
'GMR Power and Urban Infra Limited':'GMRP&UI',
'GNA Axles Limited':'GNA',
'Gujarat Narmada Valley Fertilizers and Chemicals Limited':'GNFC',
'Goa Carbon Limited':'GOACARBON',
'GOCL Corporation Limited':'GOCLCORP',
'Go Fashion (India) Limited':'GOCOLORS',
'Godfrey Phillips India Limited':'GODFRYPHLP',
'Godha Cabcon & Insulation Limited':'GODHA',
'Go Digit General Insurance Limited':'GODIGIT',
'Godrej Agrovet Limited':'GODREJAGRO',
'Godrej Consumer Products Limited':'GODREJCP',
'Godrej Industries Limited':'GODREJIND',
'Godrej Properties Limited':'GODREJPROP',
'Gokaldas Exports Limited':'GOKEX',
'Gokul Refoils and Solvent Limited':'GOKUL',
'Gokul Agro Resources Limited':'GOKULAGRO',
'Goldiam International Limited':'GOLDIAM',
'AION-TECH SOLUTIONS LIMITED':'GOLDTECH',
'Goodluck India Limited':'GOODLUCK',
'Gopal Snacks Limited':'GOPAL',
'Goyal Aluminiums Limited':'GOYALALUM',
'Godawari Power And Ispat limited':'GPIL',
'Gujarat Pipavav Port Limited':'GPPL',
'GPT Healthcare Limited':'GPTHEALTH',
'GPT Infraprojects Limited':'GPTINFRA',
'Granules India Limited':'GRANULES',
'Graphite India Limited':'GRAPHITE',
'Grasim Industries Limited':'GRASIM',
'Gravita India Limited':'GRAVITA',
'Greaves Cotton Limited':'GREAVESCOT',
'Greenlam Industries Limited':'GREENLAM',
'Greenpanel Industries Limited':'GREENPANEL',
'Greenply Industries Limited':'GREENPLY',
'Orient Green Power Company Limited':'GREENPOWER',
'Grindwell Norton Limited':'GRINDWELL',
'G R Infraprojects Limited':'GRINFRA',
'GRM Overseas Limited':'GRMOVER',
'GRP Limited':'GRPLTD',
'Garden Reach Shipbuilders & Engineers Limited':'GRSE',
'Garware Hi-Tech Films Limited':'GRWRHITECH',
'Gujarat State Fertilizers & Chemicals Limited':'GSFC',
'Global Surfaces Limited':'GSLSU',
'Gujarat State Petronet Limited':'GSPL',
'GSS Infotech Limited':'GSS',
'GTL Limited':'GTL',
'GTL Infrastructure Limited':'GTLINFRA',
'GTPL Hathway Limited':'GTPL',
'Gufic Biosciences Limited':'GUFICBIO',
'Gujarat Alkalies and Chemicals Limited':'GUJALKALI',
'Gujarat Apollo Industries Limited':'GUJAPOLLO',
'Gujarat Gas Limited':'GUJGASLTD',
'Gujarat Themis Biosyn Limited':'GUJTHEM',
'Gulf Oil Lubricants India Limited':'GULFOILLUB',
'GP Petroleums Limited':'GULFPETRO',
'Gulshan Polyols Limited':'GULPOLY',
'GVP Infotech Limited':'GVPTECH',
'GE Vernova T&D India Limited':'GVT&D',
'Hindustan Aeronautics Limited':'HAL',
'Happiest Minds Technologies Limited':'HAPPSTMNDS',
'Happy Forgings Limited':'HAPPYFORGE',
'Hariom Pipe Industries Limited':'HARIOMPIPE',
'Harrisons  Malayalam Limited':'HARRMALAYA',
'Harsha Engineers International Limited':'HARSHA',
'Hathway Cable & Datacom Limited':'HATHWAY',
'Hatsun Agro Product Limited':'HATSUN',
'Havells India Limited':'HAVELLS',
'Sri Havisha Hospitality and Infrastructure Limited':'HAVISHA',
'HBL Engineering Limited':'HBLENGINE',
'Healthcare Global Enterprises Limited':'HCG',
'HCL Technologies Limited':'HCLTECH',
'HDB Financial Services Limited':'HDBFS',
'HDFC Asset Management Company Limited':'HDFCAMC',
'HDFC Bank Limited':'HDFCBANK',
'HDFC Life Insurance Company Limited':'HDFCLIFE',
'Heads UP Ventures Limited':'HEADSUP',
'HEG Limited':'HEG',
'HeidelbergCement India Limited':'HEIDELBERG',
'Hemisphere Properties India Limited':'HEMIPROP',
'Heranba Industries Limited':'HERANBA',
'Heritage Foods Limited':'HERITGFOOD',
'Hero MotoCorp Limited':'HEROMOTOCO',
'Hester Biosciences Limited':'HESTERBIO',
'Heubach Colorants India Limited':'HEUBACHIND',
'Hexa Tradex Limited':'HEXATRADEX',
'Hexaware Technologies Limited':'HEXT',
'HFCL Limited':'HFCL',
'H.G. Infra Engineering Limited':'HGINFRA',
'Hinduja Global Solutions Limited':'HGS',
'Hikal Limited':'HIKAL',
'Himatsingka Seide Limited':'HIMATSEIDE',
'Hindalco Industries Limited':'HINDALCO',
'Hindustan Composites Limited':'HINDCOMPOS',
'Hindcon Chemicals Limited':'HINDCON',
'Hindustan Copper Limited':'HINDCOPPER',
'Hindustan Oil Exploration Company Limited':'HINDOILEXP',
'Hindustan Petroleum Corporation Limited':'HINDPETRO',
'Hindustan Unilever Limited':'HINDUNILVR',
'Hindware Home Innovation Limited':'HINDWAREAP',
'Hindustan Zinc Limited':'HINDZINC',
'Hind Rectifiers Limited':'HIRECT',
'Hisar Metal Industries Limited':'HISARMETAL',
'Hi-Tech Pipes Limited':'HITECH',
'Hitech Corporation Limited':'HITECHCORP',
'HLE Glascoat Limited':'HLEGLAS',
'HLV LIMITED':'HLVLTD',
'HMA Agro Industries Limited':'HMAAGRO',
'Hindustan Media Ventures Limited':'HMVL',
'Hindustan Foods Limited':'HNDFDS',
'Home First Finance Company India Limited':'HOMEFIRST',
'Honasa Consumer Limited':'HONASA',
'Honeywell Automation India Limited':'HONAUT',
'Honda India Power Products Limited':'HONDAPOWER',
'HP Adhesives Limited':'HPAL',
'Hindprakash Industries Limited':'HPIL',
'HPL Electric & Power Limited':'HPL',
'Himadri Speciality Chemical Limited':'HSCL',
'Hubtown Limited':'HUBTOWN',
'Housing & Urban Development Corporation Limited':'HUDCO',
'Huhtamaki India Limited':'HUHTAMAKI',
'Hyundai Motor India Limited':'HYUNDAI',
'Ice Make Refrigeration Limited':'ICEMAKE',
'ICICI Bank Limited':'ICICIBANK',
'ICICI Lombard General Insurance Company Limited':'ICICIGI',
'ICICI Prudential Life Insurance Company Limited':'ICICIPRULI',
'Indo Count Industries Limited':'ICIL',
'ICRA Limited':'ICRA',
'IDBI Bank Limited':'IDBI',
'Vodafone Idea Limited':'IDEA',
'Ideaforge Technology Limited':'IDEAFORGE',
'IDFC First Bank Limited':'IDFCFIRSTB',
'Indian Energy Exchange Limited':'IEX',
'IFB Industries Limited':'IFBIND',
'IFCI Limited':'IFCI',
'IFGL Refractories Limited':'IFGLEXPOR',
'Igarashi Motors India Limited':'IGARASHI',
'International Gemmological Institute (India) Limited':'IGIL',
'Indraprastha Gas Limited':'IGL',
'IG Petrochemicals Limited':'IGPL',
'IIFL Finance Limited':'IIFL',
'IIFL Capital Services Limited':'IIFLCAPS',
'IKIO Technologies Limited':'IKIO',
'Inventurus Knowledge Solutions Limited':'IKS',
'Imagicaaworld Entertainment Limited':'IMAGICAA',
'Indian Metals & Ferro Alloys Limited':'IMFA',
'India Motor Parts and Accessories Limited':'IMPAL',
'Indbank Merchant Banking Services Limited':'INDBANK',
'Indegene Limited':'INDGN',
'The Indian Hotels Company Limited':'INDHOTEL',
'The India Cements Limited':'INDIACEM',
'India Glycols Limited':'INDIAGLYCO',
'Indiamart Intermesh Limited':'INDIAMART',
'Indian Bank':'INDIANB',
'Indian Card Clothing Company Limited':'INDIANCARD',
'Indian Hume Pipe Company Limited':'INDIANHUME',
'India Shelter Finance Corporation Limited':'INDIASHLTR',
'InterGlobe Aviation Limited':'INDIGO',
'Indigo Paints Limited':'INDIGOPNTS',
'India Nippon Electricals Limited':'INDNIPPON',
'Indo Amines Limited':'INDOAMIN',
'Indo Borax & Chemicals Limited':'INDOBORAX',
'Indoco Remedies Limited':'INDOCO',
'IndoStar Capital Finance Limited':'INDOSTAR',
'Indo Tech Transformers Limited':'INDOTECH',
'Indo Us Biotech Limited':'INDOUS',
'Indowind Energy Limited':'INDOWIND',
'Indraprastha Medical Corporation Limited':'INDRAMEDCO',
'Ind-Swift Laboratories Limited':'INDSWFTLAB',
'Ind-Swift Limited':'INDSWFTLTD',
'Indian Terrain Fashions Limited':'INDTERRAIN',
'IndusInd Bank Limited':'INDUSINDBK',
'Indus Towers Limited':'INDUSTOWER',
'Infibeam Avenues Limited':'INFIBEAM',
'InfoBeans Technologies Limited':'INFOBEAN',
'Infosys Limited':'INFY',
'Ingersoll Rand (India) Limited':'INGERRAND',
'Innova Captab Limited':'INNOVACAP',
'Innovana Thinklabs Limited':'INNOVANA',
'INOX India Limited':'INOXINDIA',
'Inox Wind Limited':'INOXWIND',
'Insecticides (India) Limited':'INSECTICID',
'Intellect Design Arena Limited':'INTELLECT',
'Intense Technologies Limited':'INTENTECH',
'International Conveyors Limited':'INTLCONV',
'Inventure Growth & Securities Limited':'INVENTURE',
'Indian Overseas Bank':'IOB',
'Indian Oil Corporation Limited':'IOC',
'IOL Chemicals and Pharmaceuticals Limited':'IOLCP',
'ION Exchange (India) Limited':'IONEXCHANG',
'IPCA Laboratories Limited':'IPCALAB',
'India Pesticides Limited':'IPL',
'IRB Infrastructure Developers Limited':'IRB',
'Ircon International Limited':'IRCON',
'Indian Railway Catering And Tourism Corporation Limited':'IRCTC',
'Indian Renewable Energy Development Agency Limited':'IREDA',
'Indian Railway Finance Corporation Limited':'IRFC',
'Iris Business Services Limited':'IRIS',
'IRM Energy Limited':'IRMENERGY',
'Intrasoft Technologies Limited':'ISFT',
'Isgec Heavy Engineering Limited':'ISGEC',
'Ishan Dyes and Chemicals Limited':'ISHANCH',
'ITC Limited':'ITC',
'ITC Hotels Limited':'ITCHOTELS',
'India Tourism Development Corporation Limited':'ITDC',
'ITD Cementation India Limited':'ITDCEM',
'ITI Limited':'ITI',
'IL&FS Investment Managers Limited':'IVC',
'IVP Limited':'IVP',
'Le Travenues Technology Limited':'IXIGO',
'The Jammu & Kashmir Bank Limited':'J&KBANK',
'Jagran Prakashan Limited':'JAGRAN',
'Jagsonpal Pharmaceuticals Limited':'JAGSNPHARM',
'Jai Balaji Industries Limited':'JAIBALAJI',
'Jai Corp Limited':'JAICORPLTD',
'Nandani Creation Limited':'JAIPURKURT',
'Jamna Auto Industries Limited':'JAMNAAUTO',
'Jash Engineering Limited':'JASH',
'Jayant Agro Organics Limited':'JAYAGROGN',
'Jay Bharat Maruti Limited':'JAYBARMARU',
'Jayaswal Neco Industries Limited':'JAYNECOIND',
'Jayshree Tea & Industries Limited':'JAYSREETEA',
'JB Chemicals & Pharmaceuticals Limited':'JBCHEPHARM',
'JBM Auto Limited':'JBMA',
'Johnson Controls - Hitachi Air Conditioning India Limited':'JCHAC',
'Jet Freight Logistics Limited':'JETFREIGHT',
'J.G.Chemicals Limited':'JGCHEM',
'JHS Svendgaard Laboratories Limited':'JHS',
'Jindal Poly Films Limited':'JINDALPOLY',
'Jindal Saw Limited':'JINDALSAW',
'Jindal Steel & Power Limited':'JINDALSTEL',
'Jindal Drilling And Industries Limited':'JINDRILL',
'Jindal Worldwide Limited':'JINDWORLD',
'Jio Financial Services Limited':'JIOFIN',
'Jain Irrigation Systems Limited':'JISLDVREQS',
'Jain Irrigation Systems Limited':'JISLJALEQS',
'JK Cement Limited':'JKCEMENT',
'J.Kumar Infraprojects Limited':'JKIL',
'JK Lakshmi Cement Limited':'JKLAKSHMI',
'JK Paper Limited':'JKPAPER',
'JK Tyre & Industries Limited':'JKTYRE',
'Jupiter Life Line Hospitals Limited':'JLHL',
'Jullundur Motor Agency (Delhi) Limited':'JMA',
'JM Financial Limited':'JMFINANCIL',
'JNK India Limited':'JNKINDIA',
'Jocil Limited':'JOCIL',
'Jindal Poly Investment and Finance Company Limited':'JPOLYINVST',
'Jaiprakash Power Ventures Limited':'JPPOWER',
'Jana Small Finance Bank Limited':'JSFB',
'Jindal Stainless Limited':'JSL',
'JSW Energy Limited':'JSWENERGY',
'JSW Infrastructure Limited':'JSWINFRA',
'JSW Steel Limited':'JSWSTEEL',
'Jtekt India Limited':'JTEKTINDIA',
'JTL INDUSTRIES LIMITED':'JTLIND',
'Jubilant Agri and Consumer Products Limited':'JUBLCPL',
'Jubilant Foodworks Limited':'JUBLFOOD',
'Jubilant Ingrevia Limited':'JUBLINGREA',
'Jubilant Pharmova Limited':'JUBLPHARMA',
'Juniper Hotels Limited':'JUNIPER',
'Just Dial Limited':'JUSTDIAL',
'Jupiter Wagons Limited':'JWL',
'Jyothy Labs Limited':'JYOTHYLAB',
'Jyoti CNC Automation Limited':'JYOTICNC',
'Jyoti Structures Limited':'JYOTISTRUC',
'Kajaria Ceramics Limited':'KAJARIACER',
'Kakatiya Cement Sugar & Industries Limited':'KAKATCEM',
'Sai Silks (Kalamandir) Limited':'KALAMANDIR',
'Kalpataru Limited':'KALPATARU',
'Kalyani Forge Limited':'KALYANIFRG',
'Kalyan Jewellers India Limited':'KALYANKJIL',
'Kamat Hotels (I) Limited':'KAMATHOTEL',
'Kamdhenu Limited':'KAMDHENU',
'Kanani Industries Limited':'KANANIIND',
'Kanoria Chemicals & Industries Limited':'KANORICHEM',
'Kansai Nerolac Paints Limited':'KANSAINER',
'Kapston Services Limited':'KAPSTON',
'Karur Vysya Bank Limited':'KARURVYSYA',
'Kaushalya Infrastructure Development Corporation Limited':'KAUSHALYA',
'Kaynes Technology India Limited':'KAYNES',
'KCP Limited':'KCP',
'KCP Sugar and Industries Corporation Limited':'KCPSUGIND',
'KDDL Limited':'KDDL',
'KEC International Limited':'KEC',
'Kirloskar Electric Company Limited':'KECL',
'KEI Industries Limited':'KEI',
'Kellton Tech Solutions Limited':'KELLTONTEC',
'Kfin Technologies Limited':'KFINTECH',
'Khadim India Limited':'KHADIM',
'Khandwala Securities Limited':'KHANDSE',
'Kalyani Investment Company Limited':'KICL',
'Krishna Institute of Medical Sciences Limited':'KIMS',
'Kingfa Science & Technology (India) Limited':'KINGFA',
'KIOCL Limited':'KIOCL',
'Kiri Industries Limited':'KIRIINDUS',
'Kirloskar Brothers Limited':'KIRLOSBROS',
'Kirloskar Oil Engines Limited':'KIRLOSENG',
'Kirloskar Industries Limited':'KIRLOSIND',
'Kirloskar Pneumatic Company Limited':'KIRLPNU',
'Kitex Garments Limited':'KITEX',
'Kewal Kiran Clothing Limited':'KKCL',
'Knowledge Marine & Engineering Works Limited':'KMEW',
'K.M.Sugar Mills Limited':'KMSUGAR',
'KNR Constructions Limited':'KNRCON',
'Kohinoor Foods Limited':'KOHINOOR',
'Kokuyo Camlin Limited':'KOKUYOCMLN',
'Kolte - Patil Developers Limited':'KOLTEPATIL',
'Kopran Limited':'KOPRAN',
'Kotak Mahindra Bank Limited':'KOTAKBANK',
'Kothari Sugars And Chemicals Limited':'KOTARISUG',
'Kothari Petrochemicals Limited':'KOTHARIPET',
'Kothari Products Limited':'KOTHARIPRO',
'K.P. Energy Limited':'KPEL',
'KPI Green Energy Limited':'KPIGREEN',
'Kalpataru Projects International Limited':'KPIL',
'KPIT Technologies Limited':'KPITTECH',
'K.P.R. Mill Limited':'KPRMILL',
'KRBL Limited':'KRBL',
'Krishana Phoschem Limited':'KRISHANA',
'Kritika Wires Limited':'KRITIKA',
'Kriti Nutrients Limited':'KRITINUT',
'KRN Heat Exchanger and Refrigeration Limited':'KRN',
'Kronox Lab Sciences Limited':'KRONOX',
'Kross Limited':'KROSS',
'Krsnaa Diagnostics Limited':'KRSNAA',
'Ksb Limited':'KSB',
'Kaveri Seed Company Limited':'KSCL',
'Kshitij Polyline Limited':'KSHITIJPOL',
'Kalyani Steels Limited':'KSL',
'Ksolves India Limited':'KSOLVES',
'The Karnataka Bank Limited':'KTKBANK',
'Kuantum Papers Limited':'KUANTUM',
'Lagnam Spintex Limited':'LAGNAM',
'Dr. Lal Path Labs Ltd.':'LALPATHLAB',
'Lambodhara Textiles Limited':'LAMBODHARA',
'Lancor Holdings Limited':'LANCORHOL',
'Landmark Cars Limited':'LANDMARK',
'La Opala RG Limited':'LAOPALA',
'Latent View Analytics Limited':'LATENTVIEW',
'Latteys Industries Limited':'LATTEYS',
'Laurus Labs Limited':'LAURUSLABS',
'Laxmi Cotspin Limited':'LAXMICOT',
'Laxmi Dental Limited':'LAXMIDENTL',
'Lemon Tree Hotels Limited':'LEMONTREE',
'Lexus Granito (India) Limited':'LEXUS',
'Lakshmi Finance & Industrial Corporation Limited':'LFIC',
'LG Balakrishnan & Bros Limited':'LGBBROSLTD',
'Laxmi Goldorna House Limited':'LGHL',
'Libas Consumer Products Limited':'LIBAS',
'LIC Housing Finance Limited':'LICHSGFIN',
'Life Insurance Corporation Of India':'LICI',
'Likhitha Infrastructure Limited':'LIKHITHA',
'Lincoln Pharmaceuticals Limited':'LINCOLN',
'Linde India Limited':'LINDEINDIA',
'LLOYDS ENGINEERING WORKS LIMITED':'LLOYDSENGG',
'Lloyds Enterprises Limited':'LLOYDSENT',
'Lloyds Metals And Energy Limited':'LLOYDSME',
'LMW Limited':'LMW',
'Macrotech Developers Limited':'LODHA',
'Lords Chloro Alkali Limited':'LORDSCHLO',
'Lotus Eye Hospital and Institute Limited':'LOTUSEYE',
'Lovable Lingerie Limited':'LOVABLE',
'Loyal Textile Mills Limited':'LOYALTEX',
'Landmark Property Development Company Limited':'LPDC',
'Larsen & Toubro Limited':'LT',
'L&T Finance Limited':'LTF',
'LT Foods Limited':'LTFOODS',
'LTIMindtree Limited':'LTIM',
'L&T Technology Services Limited':'LTTS',
'Lumax Industries Limited':'LUMAXIND',
'Lumax Auto Technologies Limited':'LUMAXTECH',
'Lupin Limited':'LUPIN',
'Lux Industries Limited':'LUXIND',
'Laxmi Organic Industries Limited':'LXCHEM',
'Lyka Labs Limited':'LYKALABS',
'Mahindra & Mahindra Limited':'M&M',
'Mahindra & Mahindra Financial Services Limited':'M&MFIN',
'Madhav Marbles and Granites Limited':'MADHAV',
'Madras Fertilizers Limited':'MADRASFERT',
'Magadh Sugar & Energy Limited':'MAGADSUGAR',
'Magnum Ventures Limited':'MAGNUM',
'Bank of Maharashtra':'MAHABANK',
'Maha Rashtra Apex Corporation Limited':'MAHAPEXLTD',
'Mahindra EPC Irrigation Limited':'MAHEPC',
'Maheshwari Logistics Limited':'MAHESHWARI',
'Mahindra Lifespace Developers Limited':'MAHLIFE',
'Mahindra Logistics Limited':'MAHLOG',
'Maharashtra Scooters Limited':'MAHSCOOTER',
'Maharashtra Seamless Limited':'MAHSEAMLES',
'Maithan Alloys Limited':'MAITHANALL',
'Mallcom (India) Limited':'MALLCOM',
'Malu Paper Mills Limited':'MALUPAPER',
'Mamata Machinery Limited':'MAMATA',
'Manaksia Aluminium Company Limited':'MANAKALUCO',
'Manaksia Coated Metals & Industries Limited':'MANAKCOAT',
'Manaksia Limited':'MANAKSIA',
'Manaksia Steels Limited':'MANAKSTEEL',
'Manali Petrochemicals Limited':'MANALIPETC',
'Manappuram Finance Limited':'MANAPPURAM',
'Manba Finance Limited':'MANBA',
'Mangal Credit and Fincorp Limited':'MANCREDIT',
'Mangalam Drugs And Organics Limited':'MANGALAM',
'Mangalore Chemicals & Fertilizers Limited':'MANGCHEFER',
'Mangalam Cement Limited':'MANGLMCEM',
'Man Industries (India) Limited':'MANINDS',
'Man Infraconstruction Limited':'MANINFRA',
'Mankind Pharma Limited':'MANKIND',
'Manomay Tex India Limited':'MANOMAY',
'Manorama Industries Limited':'MANORAMA',
'Vedant Fashions Limited':'MANYAVAR',
'C.E. Info Systems Limited':'MAPMYINDIA',
'Maral Overseas Limited':'MARALOVER',
'Marathon Nextgen Realty Limited':'MARATHON',
'Marico Limited':'MARICO',
'Marksans Pharma Limited':'MARKSANS',
'Maruti Suzuki India Limited':'MARUTI',
'MAS Financial Services Limited':'MASFIN',
'Mastek Limited':'MASTEK',
'Master Trust Limited':'MASTERTR',
'Matrimony.Com Limited':'MATRIMONY',
'Mawana Sugars Limited':'MAWANASUG',
'Max Estates Limited':'MAXESTATES',
'Max Healthcare Institute Limited':'MAXHEALTH',
'Max India Limited':'MAXIND',
'Mayur Uniquoters Ltd':'MAYURUNIQ',
'Mazda Limited':'MAZDA',
'Mazagon Dock Shipbuilders Limited':'MAZDOCK',
'Madhya Bharat Agro Products Limited':'MBAPL',
'MBL Infrastructure Limited':'MBLINFRA',
'Madhav Copper Limited':'MCL',
'Mcleod Russel India Limited':'MCLEODRUSS',
'Magellanic Cloud Limited':'MCLOUD',
'Multi Commodity Exchange of India Limited':'MCX',
'Global Health Limited':'MEDANTA',
'Medi Assist Healthcare Services Limited':'MEDIASSIST',
'Medicamen Biotech Limited':'MEDICAMEQ',
'Medico Remedies Limited':'MEDICO',
'Medplus Health Services Limited':'MEDPLUS',
'Megastar Foods Limited':'MEGASTAR',
'Menon Bearings Limited':'MENONBE',
'Metro Brands Limited':'METROBRAND',
'Metropolis Healthcare Limited':'METROPOLIS',
'Max Financial Services Limited':'MFSL',
'Mangalam Global Enterprise Limited':'MGEL',
'Mahanagar Gas Limited':'MGL',
'Mahalaxmi Rubtech Limited':'MHLXMIRU',
'Mahindra Holidays & Resorts India Limited':'MHRIL',
'MIC Electronics Limited':'MICEL',
'Mishra Dhatu Nigam Limited':'MIDHANI',
'Minda Corporation Limited':'MINDACORP',
'MIRC Electronics Limited':'MIRCELECTR',
'Mirza International Limited':'MIRZAINT',
'MITCON Consultancy & Engineering Services Limited':'MITCON',
'Mittal Life Style Limited':'MITTAL',
'MM Forgings Limited':'MMFL',
'MMP Industries Limited':'MMP',
'MMTC Limited':'MMTC',
'One Mobikwik Systems Limited':'MOBIKWIK',
'MODISON LIMITED':'MODISONLTD',
'Modern Threads (India) Limited':'MODTHREAD',
'Mohit Industries Limited':'MOHITIND',
'MOIL Limited':'MOIL',
'Moksh Ornaments Limited':'MOKSH',
'Meghmani Organics Limited':'MOL',
'Mold-Tek Technologies Limited':'MOLDTECH',
'Mold-Tek Packaging Limited':'MOLDTKPAC',
'Monarch Networth Capital Limited':'MONARCH',
'Monte Carlo Fashions Limited':'MONTECARLO',
'Morepen Laboratories Limited':'MOREPENLAB',
'Moschip Technologies Limited':'MOSCHIP',
'Samvardhana Motherson International Limited':'MOTHERSON',
'Motilal Oswal Financial Services Limited':'MOTILALOFS',
'Motisons Jewellers Limited':'MOTISONS',
'The Motor & General Finance Limited':'MOTOGENFIN',
'MphasiS Limited':'MPHASIS',
'MPS Limited':'MPSLTD',
'MRF Limited':'MRF',
'Mangalore Refinery and Petrochemicals Limited':'MRPL',
'MSP Steel & Power Limited':'MSPL',
'Mstc Limited':'MSTCLTD',
'Motherson Sumi Wiring India Limited':'MSUMI',
'Mtar Technologies Limited':'MTARTECH',
'Mahanagar Telephone Nigam Limited':'MTNL',
'Mufin Green Finance Limited':'MUFIN',
'Credo Brands Marketing Limited':'MUFTI',
'Mukand Limited':'MUKANDLTD',
'Mukka Proteins Limited':'MUKKA',
'Mukta Arts Limited':'MUKTAARTS',
'Munjal Auto Industries Limited':'MUNJALAU',
'Munjal Showa Limited':'MUNJALSHOW',
'Murudeshwar Ceramics Limited':'MURUDCERA',
'Muthoot Capital Services Limited':'MUTHOOTCAP',
'Muthoot Finance Limited':'MUTHOOTFIN',
'Muthoot Microfin Limited':'MUTHOOTMF',
'Manoj Vaibhav Gems N Jewellers Limited':'MVGJL',
'Nagreeka Capital & Infrastructure Limited':'NAGREEKCAP',
'Nagreeka Exports Limited':'NAGREEKEXP',
'Nahar Spinning Mills Limited':'NAHARSPING',
'Nippon Life India Asset Management Limited':'NAM-INDIA',
'Narmada Agrobase Limited':'NARMADA',
'Natural Capsules Limited':'NATCAPSUQ',
'Natco Pharma Limited':'NATCOPHARM',
'Nath Bio-Genes (India) Limited':'NATHBIOGEN',
'National Aluminium Company Limited':'NATIONALUM',
'Info Edge (India) Limited':'NAUKRI',
'NAVA LIMITED':'NAVA',
'Navin Fluorine International Limited':'NAVINFLUOR',
'Navkar Corporation Limited':'NAVKARCORP',
'Navneet Education Limited':'NAVNETEDUL',
'Nazara Technologies Limited':'NAZARA',
'NBCC (India) Limited':'NBCC',
'N. B. I. Industrial Finance Company Limited':'NBIFIN',
'NCC Limited':'NCC',
'NCL Industries Limited':'NCLIND',
'Naga Dhunseri Group Limited':'NDGL',
'Nandan Denim Limited':'NDL',
'Ndr Auto Components Limited':'NDRAUTO',
'North Eastern Carrying Corporation Limited':'NECCLTD',
'Nectar Lifesciences Limited':'NECLIFE',
'Nelcast Limited':'NELCAST',
'NELCO Limited':'NELCO',
'Neogen Chemicals Limited':'NEOGEN',
'Nesco Limited':'NESCO',
'Nestle India Limited':'NESTLEIND',
'Netweb Technologies India Limited':'NETWEB',
'Network18 Media & Investments Limited':'NETWORK18',
'Neuland Laboratories Limited':'NEULANDLAB',
'Newgen Software Technologies Limited':'NEWGEN',
'Next Mediaworks Limited':'NEXTMEDIA',
'National Fertilizers Limited':'NFL',
'Nakoda Group of Industries Limited':'NGIL',
'Narayana Hrudayalaya Ltd.':'NH',
'NHPC Limited':'NHPC',
'The New India Assurance Company Limited':'NIACL',
'NIBE Limited':'NIBE',
'NIIT Limited':'NIITLTD',
'NIIT Learning Systems Limited':'NIITMTS',
'Nila Infrastructures Limited':'NILAINFRA',
'Nila Spaces Limited':'NILASPACES',
'Nilkamal Limited':'NILKAMAL',
'NINtec Systems Limited':'NINSYS',
'Indo-National Limited':'NIPPOBATRY',
'Niraj Cement Structurals Limited':'NIRAJ',
'Nitco Limited':'NITCO',
'Nitin Spinners Limited':'NITINSPIN',
'Nitiraj Engineers Limited':'NITIRAJ',
'Niva Bupa Health Insurance Company Limited':'NIVABUPA',
'NK Industries Limited':'NKIND',
'NLC India Limited':'NLCINDIA',
'NMDC Limited':'NMDC',
'NOCIL Limited':'NOCIL',
'Northern Arc Capital Limited':'NORTHARC',
'Nova Agritech Limited':'NOVAAGRI',
'Network People Services Technologies Limited':'NPST',
'NRB Bearing Limited':'NRBBEARING',
'Nalwa Sons Investments Limited':'NSIL',
'NMDC Steel Limited':'NSLNISP',
'NTPC Limited':'NTPC',
'NTPC Green Energy Limited':'NTPCGREEN',
'Nucleus Software Exports Limited':'NUCLEUS',
'Nuvama Wealth Management Limited':'NUVAMA',
'Nuvoco Vistas Corporation Limited':'NUVOCO',
'FSN E-Commerce Ventures Limited':'NYKAA',
'Oriental Aromatics Limited':'OAL',
'Orissa Bengal Carrier Limited':'OBCL',
'Oberoi Realty Limited':'OBEROIRLTY',
'Oracle Financial Services Software Limited':'OFSS',
'Oil India Limited':'OIL',
'Oil Country Tubular Limited':'OILCOUNTUB',
'Ola Electric Mobility Limited':'OLAELEC',
'Olectra Greentech Limited':'OLECTRA',
'Omax Autos Limited':'OMAXAUTO',
'Omaxe Limited':'OMAXE',
'OM INFRA LIMITED':'OMINFRAL',
'Onesource Specialty Pharma Limited':'ONESOURCE',
'Oil & Natural Gas Corporation Limited':'ONGC',
'OnMobile Global Limited':'ONMOBILE',
'Optiemus Infracom Limited':'OPTIEMUS',
'Orchid Pharma Limited':'ORCHPHARMA',
'Oricon Enterprises Limited':'ORICONENT',
'Orient Bell Limited':'ORIENTBELL',
'Orient Cement Limited':'ORIENTCEM',
'ORIENT CERATECH LIMITED':'ORIENTCER',
'Orient Electric Limited':'ORIENTELEC',
'Oriental Hotels Limited':'ORIENTHOT',
'Orient Press Limited':'ORIENTLTD',
'Orient Paper & Industries Limited':'ORIENTPPR',
'Orient Technologies Limited':'ORIENTTECH',
'The Orissa Minerals Development Company Limited':'ORISSAMINE',
'Oswal Agro Mills Limited':'OSWALAGRO',
'Oswal Greentech Limited':'OSWALGREEN',
'Oswal Pumps Limited':'OSWALPUMPS',
'ShreeOswal Seeds And Chemicals Limited':'OSWALSEEDS',
'Page Industries Limited':'PAGEIND',
'Paisalo Digital Limited':'PAISALO',
'PAKKA LIMITED':'PAKKA',
'Palash Securities Limited':'PALASHSECU',
'Panacea Biotec Limited':'PANACEABIO',
'Panama Petrochem Limited':'PANAMAPET',
'Paramount Communications Limited':'PARACABLES',
'Paradeep Phosphates Limited':'PARADEEP',
'Parag Milk Foods Limited':'PARAGMILK',
'Paras Defence and Space Technologies Limited':'PARAS',
'Paras Petrofils Limited':'PARASPETRO',
'Apeejay Surrendra Park Hotels Limited':'PARKHOTELS',
'Parsvnath Developers Limited':'PARSVNATH',
'Pasupati Acrylon Limited':'PASUPTAC',
'Patanjali Foods Limited':'PATANJALI',
'Patel Engineering Limited':'PATELENG',
'Patel Integrated Logistics Limited':'PATINTLOG',
'Pavna Industries Limited':'PAVNAIND',
'One 97 Communications Limited':'PAYTM',
'PCBL Chemical Limited':'PCBL',
'PC Jeweller Limited':'PCJEWELLER',
'Pudumjee Paper Products Limited':'PDMJEPAPER',
'PDS Limited':'PDSL',
'Pearl Polymers Limited':'PEARLPOLY',
'Piramal Enterprises Limited':'PEL',
'Pennar Industries Limited':'PENIND',
'Persistent Systems Limited':'PERSISTENT',
'Petronet LNG Limited':'PETRONET',
'Power Finance Corporation Limited':'PFC',
'Pfizer Limited':'PFIZER',
'Prime Focus Limited':'PFOCUS',
'PTC India Financial Services Limited':'PFS',
'PG Electroplast Limited':'PGEL',
'Procter & Gamble Hygiene and Health Care Limited':'PGHH',
'Procter & Gamble Health Limited':'PGHL',
'Pearl Global Industries Limited':'PGIL',
'The Phoenix Mills Limited':'PHOENIXLTD',
'Piccadily Agro Industries Limited':'PICCADIL',
'Pidilite Industries Limited':'PIDILITIND',
'PI Industries Limited':'PIIND',
'Pilani Investment and Industries Corporation Limited':'PILANIINVS',
'Pioneer Embroideries Limited':'PIONEEREMB',
'Pitti Engineering Limited':'PITTIENG',
'Pix Transmissions Limited':'PIXTRANS',
'Plastiblends India Limited':'PLASTIBLEN',
'Platinum Industries Limited':'PLATIND',
'Plaza Wires Limited':'PLAZACABLE',
'Punjab National Bank':'PNB',
'PNB Gilts Limited':'PNBGILTS',
'PNB Housing Finance Limited':'PNBHOUSING',
'PNC Infratech Limited':'PNCINFRA',
'P N Gadgil Jewellers Limited':'PNGJL',
'Pondy Oxides & Chemicals Limited':'POCL',
'Poddar Pigments Limited':'PODDARMENT',
'Pokarna Limited':'POKARNA',
'PB Fintech Limited':'POLICYBZR',
'Polycab India Limited':'POLYCAB',
'Poly Medicure Limited':'POLYMED',
'Polyplex Corporation Limited':'POLYPLEX',
'Ponni Sugars (Erode) Limited':'PONNIERODE',
'Poonawalla Fincorp Limited':'POONAWALLA',
'Power Grid Corporation of India Limited':'POWERGRID',
'Hitachi Energy India Limited':'POWERINDIA',
'Power Mech Projects Limited':'POWERMECH',
'Prakash Pipes Limited':'PPL',
'Piramal Pharma Limited':'PPLPHARMA',
'Prabha Energy Limited':'PRABHA',
'Prajay Engineers Syndicate Limited':'PRAENG',
'Praj Industries Limited':'PRAJIND',
'Prakash Industries Limited':'PRAKASH',
'Prakash Steelage Limited':'PRAKASHSTL',
'Precision Camshafts Limited':'PRECAM',
'Precot Limited':'PRECOT',
'Precision Wires India Limited':'PRECWIRE',
'Premier Explosives Limited':'PREMEXPLN',
'Premier Energies Limited':'PREMIERENE',
'Premier Polyfilm Limited':'PREMIERPOL',
'Prestige Estates Projects Limited':'PRESTIGE',
'Pricol Limited':'PRICOLLTD',
'Prime Securities Limited':'PRIMESECU',
'Primo Chemicals Limited':'PRIMO',
'Prince Pipes And Fittings Limited':'PRINCEPIPE',
'Priti International Limited':'PRITI',
'Pritika Auto Industries Limited':'PRITIKAUTO',
'Privi Speciality Chemicals Limited':'PRIVISCL',
'Prostarm Info Systems Limited':'PROSTARM',
'Protean eGov Technologies Limited':'PROTEAN',
'Prozone Realty Limited':'PROZONER',
'Prism Johnson Limited':'PRSMJOHNSN',
'Prudent Corporate Advisory Services Limited':'PRUDENT',
'Prudential Sugar Corporation Limited':'PRUDMOULI',
'Punjab & Sind Bank':'PSB',
'PSP Projects Limited':'PSPPROJECT',
'PTC India Limited':'PTC',
'PTC Industries Limited':'PTCIL',
'PTL Enterprises Limited':'PTL',
'Punjab Chemicals & Crop Protection Limited':'PUNJABCHEM',
'Puravankara Limited':'PURVA',
'PVP Ventures Limited':'PVP',
'PVR INOX Limited':'PVRINOX',
'Popular Vehicles and Services Limited':'PVSL',
'Pyramid Technoplast Limited':'PYRAMID',
'Quality Power Electrical Equipments Limited':'QPOWER',
'Quadrant Future Tek Limited':'QUADFUTURE',
'Quess Corp Limited':'QUESS',
'Quick Heal Technologies Limited':'QUICKHEAL',
'Race Eco Chain Limited':'RACE',
'RACL Geartech Limited':'RACLGEAR',
'Radaan Mediaworks India Limited':'RADAAN',
'Radhika Jeweltech Limited':'RADHIKAJWE',
'Radiant Cash Management Services Limited':'RADIANTCMS',
'Radico Khaitan Limited':'RADICO',
'Music Broadcast Limited':'RADIOCITY',
'Railtel Corporation Of India Limited':'RAILTEL',
'Rain Industries Limited':'RAIN',
'Rainbow Childrens Medicare Limited':'RAINBOW',
'Rajesh Exports Limited':'RAJESHEXPO',
'Rajoo Engineers Limited':'RAJOOENG',
'Rajratan Global Wire Limited':'RAJRATAN',
'Rajshree Sugars & Chemicals Limited':'RAJSREESUG',
'Rallis India Limited':'RALLIS',
'Rama Steel Tubes Limited':'RAMASTEEL',
'The Ramco Cements Limited':'RAMCOCEM',
'Ramco Industries Limited':'RAMCOIND',
'Ramky Infrastructure Limited':'RAMKY',
'Ram Ratna Wires Limited':'RAMRAT',
'Rana Sugars Limited':'RANASUG',
'Rane Holdings Limited':'RANEHOLDIN',
'Rategain Travel Technologies Limited':'RATEGAIN',
'Ratnamani Metals & Tubes Limited':'RATNAMANI',
'Ratnaveer Precision Engineering Limited':'RATNAVEER',
'Raymond Limited':'RAYMOND',
'Raymond Lifestyle Limited':'RAYMONDLSL',
'Restaurant Brands Asia Limited':'RBA',
'RBL Bank Limited':'RBLBANK',
'RBZ Jewellers Limited':'RBZJEWEL',
'Rashtriya Chemicals and Fertilizers Limited':'RCF',
'REC Limited':'RECLTD',
'Redington Limited':'REDINGTON',
'Redtape Limited':'REDTAPE',
'Refex Industries Limited':'REFEX',
'Relaxo Footwears Limited':'RELAXO',
'Reliance Chemotex Industries Limited':'RELCHEMQ',
'Reliable Data Services Limited':'RELIABLE',
'Reliance Industries Limited':'RELIANCE',
'Religare Enterprises Limited':'RELIGARE',
'Remsons Industries Limited':'REMSONSIND',
'Shree Renuka Sugars Limited':'RENUKA',
'Repco Home Finance Limited':'REPCOHOME',
'Rudrabhishek Enterprises Limited':'REPL',
'Repro India Limited':'REPRO',
'Responsive Industries Limited':'RESPONIND',
'JHS Svendgaard Retail Ventures Limited':'RETAIL',
'Renaissance Global Limited':'RGL',
'RHI MAGNESITA INDIA LIMITED':'RHIM',
'Robust Hotels Limited':'RHL',
'Rico Auto Industries Limited':'RICOAUTO',
'Reliance Industrial Infrastructure Limited':'RIIL',
'Rishabh Instruments Limited':'RISHABH',
'Ritco Logistics Limited':'RITCO',
'RITES Limited':'RITES',
'Ravi Kumar Distilleries Limited':'RKDL',
'RKEC Projects Limited':'RKEC',
'Ramkrishna Forgings Limited':'RKFORGE',
'R K Swamy Limited':'RKSWAMY',
'Rane (Madras) Limited':'RML',
'Royal Orchid Hotels Limited':'ROHLTD',
'Rolex Rings Limited':'ROLEXRINGS',
'Raj Oil Mills Limited':'ROML',
'Rossari Biotech Limited':'ROSSARI',
'Rossell India Limited':'ROSSELLIND',
'Roto Pumps Limited':'ROTO',
'ROUTE MOBILE LIMITED':'ROUTE',
'Raghav Productivity Enhancers Limited':'RPEL',
'RPG Life Sciences Limited':'RPGLIFE',
'Rajshree Polypack Limited':'RPPL',
'RPSG VENTURES LIMITED':'RPSGVENT',
'Rashi Peripherals Limited':'RPTECH',
'R R Kabel Limited':'RRKABEL',
'RSWM Limited':'RSWM',
'R Systems International Limited':'RSYSTEMS',
'RattanIndia Enterprises Limited':'RTNINDIA',
'RattanIndia Power Limited':'RTNPOWER',
'Rubfila International Limited':'RUBFILA',
'The Ruby Mills Limited':'RUBYMILLS',
'Ruchira Papers Limited':'RUCHIRA',
'Rupa & Company Limited':'RUPA',
'Rushil Decor Limited':'RUSHIL',
'Keystone Realtors Limited':'RUSTOMJEE',
'Ravinder Heights Limited':'RVHL',
'Rail Vikas Nigam Limited':'RVNL',
'Sri Adhikari Brothers Television Network Limited':'SABTNL',
'Sadbhav Engineering Limited':'SADBHAV',
'Sadbhav Infrastructure Project Limited':'SADBHIN',
'Safari Industries (India) Limited':'SAFARI',
'Sagardeep Alloys Limited':'SAGARDEEP',
'Sagar Cements Limited':'SAGCEM',
'Sagility India Limited':'SAGILITY',
'Sahyadri Industries Limited':'SAHYADRI',
'Steel Authority of India Limited':'SAIL',
'Sai Life Sciences Limited':'SAILIFE',
'Sakthi Sugars Limited':'SAKHTISUG',
'Saksoft Limited':'SAKSOFT',
'Salasar Techno Engineering Limited':'SALASAR',
'Salona Cotspin Limited':'SALONA',
'S.A.L. Steel Limited':'SALSTEEL',
'Salzer Electronics Limited':'SALZERELEC',
'Sambhaav Media Limited':'SAMBHAAV',
'Sambhv Steel Tubes Limited':'SAMBHV',
'Samhi Hotels Limited':'SAMHI',
'Sammaan Capital Limited':'SAMMAANCAP',
'Sampann Utpadan India Limited':'SAMPANN',
'Sanathan Textiles Limited':'SANATHAN',
'The Sandesh Limited':'SANDESH',
'Sandhar Technologies Limited':'SANDHAR',
'Sandur Manganese & Iron Ores Limited':'SANDUMA',
'Sangam (India) Limited':'SANGAMIND',
'Sanghi Industries Limited':'SANGHIIND',
'Sanghvi Movers Limited':'SANGHVIMOV',
'Sanginita Chemicals Limited':'SANGINITA',
'Sanofi India Limited':'SANOFI',
'Sanofi Consumer Healthcare India Limited':'SANOFICONR',
'Sansera Engineering Limited':'SANSERA',
'Sanstar Limited':'SANSTAR',
'Sapphire Foods India Limited':'SAPPHIRE',
'Sarda Energy & Minerals Limited':'SARDAEN',
'Saregama India Limited':'SAREGAMA',
'Sarveshwar Foods Limited':'SARVESHWAR',
'Sasken Technologies Limited':'SASKEN',
'Sastasundar Ventures Limited':'SASTASUNDR',
'Satia Industries Limited':'SATIA',
'Satin Creditcare Network Limited':'SATIN',
'Saurashtra Cement Limited':'SAURASHCEM',
'SBC Exports Limited':'SBC',
'Shivalik Bimetal Controls Limited':'SBCL',
'SBFC Finance Limited':'SBFC',
'SBI Cards and Payment Services Limited':'SBICARD',
'SBI Life Insurance Company Limited':'SBILIFE',
'State Bank of India':'SBIN',
'Schaeffler India Limited':'SCHAEFFLER',
'S Chand And Company Limited':'SCHAND',
'Shipping Corporation Of India Limited':'SCI',
'Shipping Corporation of India Land and Assets Limited':'SCILAL',
'Scoda Tubes Limited':'SCODATUBES',
'Sheetal Cool Products Limited':'SCPL',
'Som Distilleries & Breweries Limited':'SDBL',
'Seamec Limited':'SEAMECLTD',
'Selan Exploration Technology Limited':'SELAN',
'SEMAC CONSULTANTS LIMITED':'SEMAC',
'Senco Gold Limited':'SENCO',
'Senores Pharmaceuticals Limited':'SENORES',
'SEPC Limited':'SEPC',
'Sequent Scientific Limited':'SEQUENT',
'Servotech Renewable Power System Limited':'SERVOTECH',
'Seshasayee Paper and Boards Limited':'SESHAPAPER',
'Sheela Foam Limited':'SFL',
'Synergy Green Industries Limited':'SGIL',
'Shah Alloys Limited':'SHAHALLOYS',
'Shaily Engineering Plastics Limited':'SHAILY',
'Shakti Pumps (India) Limited':'SHAKTIPUMP',
'Shalby Limited':'SHALBY',
'Shalimar Paints Limited':'SHALPAINTS',
'Shankara Building Products Limited':'SHANKARA',
'Shanthi Gears Limited':'SHANTIGEAR',
'Sharda Cropchem Limited':'SHARDACROP',
'Sharda Motor Industries Limited':'SHARDAMOTR',
'Share India Securities Limited':'SHAREINDIA',
'Shemaroo Entertainment Limited':'SHEMAROO',
'Shivalik Rasayan Limited':'SHIVALIK',
'Shivam Autotech Limited':'SHIVAMAUTO',
'Shiva Mills Limited':'SHIVAMILLS',
'Shiva Texyarn Limited':'SHIVATEX',
'S H Kelkar and Company Limited':'SHK',
'Shoppers Stop Limited':'SHOPERSTOP',
'Shradha Infraprojects Limited':'SHRADHA',
'Shree Digvijay Cement Co.Ltd':'SHREDIGCEM',
'SHREE CEMENT LIMITED':'SHREECEM',
'Shree Pushkar Chemicals & Fertilisers Limited':'SHREEPUSHK',
'Shree Rama Multi-Tech Limited':'SHREERAMA',
'Shrenik Limited':'SHRENIK',
'Shriram Pistons & Rings Limited':'SHRIPISTON',
'Shriram Finance Limited':'SHRIRAMFIN',
'Shriram Properties Limited':'SHRIRAMPPS',
'Shyam Metalics and Energy Limited':'SHYAMMETL',
'Siemens Limited':'SIEMENS',
'Sigachi Industries Limited':'SIGACHI',
'Signatureglobal (India) Limited':'SIGNATURE',
'Signpost India Limited':'SIGNPOST',
'Sikko Industries Limited':'SIKKO',
'Standard Industries Limited':'SIL',
'SIL Investments Limited':'SILINV',
'Silly Monks Entertainment Limited':'SILLYMONKS',
'Silver Touch Technologies Limited':'SILVERTUC',
'Simplex Infrastructures Limited':'SIMPLEXINF',
'Sinclairs Hotels Limited':'SINCLAIR',
'Sindhu Trade Links Limited':'SINDHUTRAD',
'Sintercom India Limited':'SINTERCOM',
'Sirca Paints India Limited':'SIRCA',
'SIS LIMITED':'SIS',
'Siyaram Silk Mills Limited':'SIYSIL',
'S.J.S. Enterprises Limited':'SJS',
'SJVN Limited':'SJVN',
'SKF India Limited':'SKFINDIA',
'Skipper Limited':'SKIPPER',
'SKY GOLD AND DIAMONDS LIMITED':'SKYGOLD',
'Smartlink Holdings Limited':'SMARTLINK',
'SMC Global Securities Limited':'SMCGLOBAL',
'SML Isuzu Limited':'SMLISUZU',
'Sarthak Metals Limited':'SMLT',
'SMS Lifesciences India Limited':'SMSLIFE',
'SMS Pharmaceuticals Limited':'SMSPHARMA',
'Snowman Logistics Limited':'SNOWMAN',
'Sobha Limited':'SOBHA',
'Softtech Engineers Limited':'SOFTTECH',
'Solara Active Pharma Sciences Limited':'SOLARA',
'Solar Industries India Limited':'SOLARINDS',
'Somany Ceramics Limited':'SOMANYCERA',
'Soma Textiles & Industries Limited':'SOMATEX',
'Somi Conveyor Beltings Limited':'SOMICONVEY',
'Sona BLW Precision Forgings Limited':'SONACOMS',
'SONAM LIMITED':'SONAMLTD',
'Sonata Software Limited':'SONATSOFTW',
'Savita Oil Technologies Limited':'SOTL',
'The South Indian Bank Limited':'SOUTHBANK',
'S. P. Apparels Limited':'SPAL',
'Spandana Sphoorty Financial Limited':'SPANDANA',
'Sun Pharma Advanced Research Company Limited':'SPARC',
'Speciality Restaurants Limited':'SPECIALITY',
'Spectrum Electrical Industries Limited':'SPECTRUM',
'Spencers Retail Limited':'SPENCERS',
'Southern Petrochemicals Industries Corporation  Limited':'SPIC',
'Supreme Petrochem Limited':'SPLPETRO',
'SPML Infra Limited':'SPMLINFRA',
'Sportking India Limited':'SPORTKING',
'Shankar Lal Rampal Dye-Chem Limited':'SRD',
'Sreeleathers Limited':'SREEL',
'SRF Limited':'SRF',
'SRG Housing Finance Limited':'SRGHFL',
'Sree Rayalaseema Hi-Strength Hypo Limited':'SRHHYPOLTD',
'SRM Contractors Limited':'SRM',
'Saraswati Saree Depot Limited':'SSDL',
'Steel Strips Wheels Limited':'SSWL',
'Stanley Lifestyles Limited':'STANLEY',
'Strides Pharma Science Limited':'STAR',
'Star Cement Limited':'STARCEMENT',
'Star Health and Allied Insurance Company Limited':'STARHEALTH',
'Star Paper Mills Limited':'STARPAPER',
'Starteck Finance Limited':'STARTECK',
'Steelcast Limited':'STEELCAS',
'Steel City Securities Limited':'STEELCITY',
'STEEL EXCHANGE INDIA LIMITED':'STEELXIND',
'Stel Holdings Limited':'STEL',
'Sterling Tools Limited':'STERTOOLS',
'Sterlite Technologies Limited':'STLTECH',
'Stove Kraft Limited':'STOVEKRAFT',
'Stylam Industries Limited':'STYLAMIND',
'Baazar Style Retail Limited':'STYLEBAAZA',
'Styrenix Performance Materials Limited':'STYRENIX',
'Subros Limited':'SUBROS',
'Sudarshan Chemical Industries Limited':'SUDARSCHEM',
'Sukhjit Starch & Chemicals Limited':'SUKHJITS',
'Sula Vineyards Limited':'SULA',
'Sumeet Industries Limited':'SUMEETINDS',
'Sumitomo Chemical India Limited':'SUMICHEM',
'Sumit Woods Limited':'SUMIT',
'Summit Securities Limited':'SUMMITSEC',
'Sundaram Clayton Limited':'SUNCLAY',
'Sundaram Multi Pap Limited':'SUNDARAM',
'Sundaram Finance Limited':'SUNDARMFIN',
'Sundaram Finance Holdings Limited':'SUNDARMHLD',
'Sundaram Brake Linings Limited':'SUNDRMBRAK',
'Sundram Fasteners Limited':'SUNDRMFAST',
'Sundrop Brands Limited':'SUNDROP',
'Sunflag Iron And Steel Company Limited':'SUNFLAG',
'Sun Pharmaceutical Industries Limited':'SUNPHARMA',
'Sunteck Realty Limited':'SUNTECK',
'Sun TV Network Limited':'SUNTV',
'Superhouse Limited':'SUPERHOUSE',
'Super Spinning Mills Limited':'SUPERSPIN',
'Suprajit Engineering Limited':'SUPRAJIT',
'Supreme Holdings & Hospitality (India) Limited':'SUPREME',
'Supreme Industries Limited':'SUPREMEIND',
'Supriya Lifescience Limited':'SUPRIYA',
'Suraj Estate Developers Limited':'SURAJEST',
'Suraj Limited':'SURAJLTD',
'Suraksha Diagnostic Limited':'SURAKSHA',
'Surana Solar Limited':'SURANASOL',
'Surana Telecom and Power Limited':'SURANAT&P',
'Suryalakshmi Cotton Mills Limited':'SURYALAXMI',
'Surya Roshni Limited':'SURYAROSNI',
'Suryoday Small Finance Bank Limited':'SURYODAY',
'Suzlon Energy Limited':'SUZLON',
'Swan Energy Limited':'SWANENERGY',
'Swaraj Engines Limited':'SWARAJENG',
'Swiggy Limited':'SWIGGY',
'Sterling and Wilson Renewable Energy Limited':'SWSOLAR',
'Symphony Limited':'SYMPHONY',
'Syngene International Limited':'SYNGENE',
'Syrma SGS Technology Limited':'SYRMA',
'Tainwala Chemical and Plastic (I) Limited':'TAINWALCHM',
'Taj GVK Hotels & Resorts Limited':'TAJGVK',
'Talbros Automotive Components Limited':'TALBROAUTO',
'Tanla Platforms Limited':'TANLA',
'TARC Limited':'TARC',
'Transformers And Rectifiers (India) Limited':'TARIL',
'Tarmat Limited':'TARMAT',
'Tarsons Products Limited':'TARSONS',
'Tasty Bite Eatables Limited':'TASTYBITE',
'Tata Chemicals Limited':'TATACHEM',
'Tata Communications Limited':'TATACOMM',
'TATA CONSUMER PRODUCTS LIMITED':'TATACONSUM',
'Tata Elxsi Limited':'TATAELXSI',
'Tata Investment Corporation Limited':'TATAINVEST',
'Tata Motors Limited':'TATAMOTORS',
'Tata Power Company Limited':'TATAPOWER',
'Tata Steel Limited':'TATASTEEL',
'Tata Technologies Limited':'TATATECH',
'Tatva Chintan Pharma Chem Limited':'TATVA',
'TBO Tek Limited':'TBOTEK',
'Tribhovandas Bhimji Zaveri Limited':'TBZ',
'Transport Corporation of India Limited':'TCI',
'TCI Express Limited':'TCIEXP',
'TCPL Packaging Limited':'TCPLPACK',
'Tata Consultancy Services Limited':'TCS',
'TD Power Systems Limited':'TDPOWERSYS',
'Teamlease Services Limited':'TEAMLEASE',
'Tech Mahindra Limited':'TECHM',
'Techno Electric & Engineering Company Limited':'TECHNOE',
'Tega Industries Limited':'TEGA',
'Tejas Networks Limited':'TEJASNET',
'Texmaco Infrastructure & Holdings Limited':'TEXINFRA',
'Texmo Pipes and Products Limited':'TEXMOPIPES',
'Texmaco Rail & Engineering Limited':'TEXRAIL',
'Tourism Finance Corporation of India Limited':'TFCILTD',
'Transwarranty Finance Limited':'TFL',
'TGB Banquets And Hotels Limited':'TGBHOTELS',
'Thangamayil Jewellery Limited':'THANGAMAYL',
'The Investment Trust Of India Limited':'THEINVEST',
'Thejo Engineering Limited':'THEJO',
'Schloss Bangalore Limited':'THELEELA',
'Themis Medicare Limited':'THEMISMED',
'Thermax Limited':'THERMAX',
'Thomas Cook  (India)  Limited':'THOMASCOOK',
'Thomas Scott (India) Limited':'THOMASCOTT',
'Thyrocare Technologies Limited':'THYROCARE',
'Tilaknagar Industries Limited':'TI',
'Technocraft Industries (India) Limited':'TIIL',
'Tube Investments of India Limited':'TIINDIA',
'Tijaria Polypipes Limited':'TIJARIA',
'Times Guaranty Limited':'TIMESGTY',
'Time Technoplast Limited':'TIMETECHNO',
'Timken India Limited':'TIMKEN',
'Tinna Rubber and Infrastructure Limited':'TINNARUBR',
'Tips Films Limited':'TIPSFILMS',
'Tips Music Limited':'TIPSMUSIC',
'Thirumalai Chemicals Limited':'TIRUMALCHM',
'TITAGARH RAIL SYSTEMS LIMITED':'TITAGARH',
'Titan Company Limited':'TITAN',
'Tamilnad Mercantile Bank Limited':'TMB',
'Tamilnadu PetroProducts Limited':'TNPETRO',
'Tamil Nadu Newsprint & Papers Limited':'TNPL',
'Tokyo Plast International Limited':'TOKYOPLAST',
'Tolins Tyres Limited':'TOLINS',
'Torrent Pharmaceuticals Limited':'TORNTPHARM',
'Torrent Power Limited':'TORNTPOWER',
'Total Transport Systems Limited':'TOTAL',
'Touchwood Entertainment Limited':'TOUCHWOOD',
'TPL Plastech Limited':'TPLPLASTEH',
'Tracxn Technologies Limited':'TRACXN',
'Transrail Lighting Limited':'TRANSRAILL',
'TRANSWORLD SHIPPING LINES LIMITED':'TRANSWORLD',
'TREJHARA SOLUTIONS LIMITED':'TREJHARA',
'Transindia Real Estate Limited':'TREL',
'Trent Limited':'TRENT',
'TRF Limited':'TRF',
'Trident Limited':'TRIDENT',
'Trigyn Technologies Limited':'TRIGYN',
'Triveni Turbine Limited':'TRITURBINE',
'Triveni Engineering & Industries Limited':'TRIVENI',
'TTK Healthcare Limited':'TTKHLTCARE',
'TTK Prestige Limited':'TTKPRESTIG',
'TVS Holdings Limited':'TVSHLTD',
'TVS Motor Company Limited':'TVSMOTOR',
'TVS Supply Chain Solutions Limited':'TVSSCS',
'TVS Srichakra Limited':'TVSSRICHAK',
'TV Today Network Limited':'TVTODAY',
'United Breweries Limited':'UBL',
'UCAL LIMITED':'UCAL',
'UCO Bank':'UCOBANK',
'Udaipur Cement Works Limited':'UDAICEMENT',
'Updater Services Limited':'UDS',
'UFLEX Limited':'UFLEX',
'UFO Moviez India Limited':'UFO',
'The Ugar Sugar Works Limited':'UGARSUGAR',
'Ugro Capital Limited':'UGROCAP',
'Ujjivan Small Finance Bank Limited':'UJJIVANSFB',
'UltraTech Cement Limited':'ULTRACEMCO',
'Usha Martin Education & Solutions Limited':'UMESLTD',
'UMIYA BUILDCON LIMITED':'UMIYA-MRO',
'Unichem Laboratories Limited':'UNICHEMLAB',
'United Drilling Tools Limited':'UNIDT',
'Unicommerce Esolutions Limited':'UNIECOM',
'Uniphos Enterprises Limited':'UNIENTER',
'Union Bank of India':'UNIONBANK',
'Uniparts India Limited':'UNIPARTS',
'United Spirits Limited':'UNITDSPR',
'United Polyfab Gujarat Limited':'UNITEDPOLY',
'The United Nilgiri Tea Estates Company Limited':'UNITEDTEA',
'Univastu India Limited':'UNIVASTU',
'Universal Cables Limited':'UNIVCABLES',
'Universus Photo Imagings Limited':'UNIVPHOTO',
'UNO Minda Limited':'UNOMINDA',
'UPL Limited':'UPL',
'Urja Global Limited':'URJA',
'Usha Martin Limited':'USHAMART',
'Udayshivakumar Infra Limited':'USK',
'UTI Asset Management Company Limited':'UTIAMC',
'Utkarsh Small Finance Bank Limited':'UTKARSHBNK',
'Uttam Sugar Mills Limited':'UTTAMSUGAR',
'U. Y. Fincorp Limited':'UYFINCORP',
'V2 Retail Limited':'V2RETAIL',
'Vadilal Industries Limited':'VADILALIND',
'Vaibhav Global Limited':'VAIBHAVGBL',
'Vaishali Pharma Limited':'VAISHALI',
'Valiant Laboratories Limited':'VALIANTLAB',
'Vardhman Acrylics Limited':'VARDHACRLC',
'Vardhman Polytex Limited':'VARDMNPOLY',
'Varroc Engineering Limited':'VARROC',
'Vascon Engineers Limited':'VASCONEQ',
'Vaswani Industries Limited':'VASWANI',
'Varun Beverages Limited':'VBL',
'Vedanta Limited':'VEDL',
'Veedol Corporation Limited':'VEEDOL',
'Venkys (India) Limited':'VENKEYS',
'Ventive Hospitality Limited':'VENTIVE',
'Venus Pipes & Tubes Limited':'VENUSPIPES',
'Veranda Learning Solutions Limited':'VERANDA',
'Vesuvius India Limited':'VESUVIUS',
'Veto Switchgears And Cables Limited':'VETO',
'V-Guard Industries Limited':'VGUARD',
'Vardhman Holdings Limited':'VHL',
'Vidhi Specialty Food Ingredients Limited':'VIDHIING',
'Vijaya Diagnostic Centre Limited':'VIJAYA',
'Viji Finance Limited':'VIJIFIN',
'Vikas EcoTech Limited':'VIKASECO',
'Vikas Lifecare Limited':'VIKASLIFE',
'Vimta Labs Limited':'VIMTALABS',
'Vinati Organics Limited':'VINATIORGA',
'Vintage Coffee And Beverages Limited':'VINCOFE',
'Vindhya Telelinks Limited':'VINDHYATEL',
'VIP Clothing Limited':'VIPCLOTHNG',
'VIP Industries Limited':'VIPIND',
'Virinchi Limited':'VIRINCHI',
'Vishnu Chemicals Limited':'VISHNU',
'Vishwaraj Sugar Industries Limited':'VISHWARAJ',
'Visagar Polytex Limited':'VIVIDHA',
'VLS Finance Limited':'VLSFINANCE',
'V-Mart Retail Limited':'VMART',
'Vishal Mega Mart Limited':'VMM',
'Voltamp Transformers Limited':'VOLTAMP',
'Voltas Limited':'VOLTAS',
'Vishnu Prakash R Punglia Limited':'VPRPL',
'Vraj Iron and Steel Limited':'VRAJ',
'VRL Logistics Limited':'VRLLOG',
'Vardhman Special Steels Limited':'VSSL',
'VST Industries Limited':'VSTIND',
'Vibhor Steel Tubes Limited':'VSTL',
'V.S.T Tillers Tractors Limited':'VSTTILLERS',
'Vardhman Textiles Limited':'VTL',
'Waaree Energies Limited':'WAAREEENER',
'Waaree Renewable Technologies Limited':'WAAREERTL',
'VA Tech Wabag Limited':'WABAG',
'Western Carriers (India) Limited':'WCIL',
'Wealth First Portfolio Managers Limited':'WEALTH',
'Websol Energy System Limited':'WEBELSOLAR',
'Weizmann Limited':'WEIZMANIND',
'Wonder Electricals Limited':'WEL',
'Welspun Corp Limited':'WELCORP',
'Welspun Enterprises Limited':'WELENT',
'Welspun Living Limited':'WELSPUNLIV',
'Wendt (India) Limited':'WENDT',
'WESTLIFE FOODWORLD LIMITED':'WESTLIFE',
'WE WIN LIMITED':'WEWIN',
'Wheels India Limited':'WHEELS',
'Whirlpool of India Limited':'WHIRLPOOL',
'Williamson Magor & Company Limited':'WILLAMAGOR',
'Windlas Biotech Limited':'WINDLAS',
'Windsor Machines Limited':'WINDMACHIN',
'The Western India Plywoods Limited':'WIPL',
'Wipro Limited':'WIPRO',
'Wockhardt Limited':'WOCKPHARMA',
'Wonderla Holidays Limited':'WONDERLA',
'Worth Peripherals Limited':'WORTH',
'West Coast Paper Mills Limited':'WSTCSTPAPR',
'Xchanging Solutions Limited':'XCHANGING',
'Xelpmoc Design And Tech Limited':'XELPMOC',
'Xpro India Limited':'XPROINDIA',
'Xtglobal Infotech Limited':'XTGLOBAL',
'Yasho Industries Limited':'YASHO',
'Yatharth Hospital & Trauma Care Services Limited':'YATHARTH',
'Yatra Online Limited':'YATRA',
'Yes Bank Limited':'YESBANK',
'Yuken India Limited':'YUKEN',
'Zaggle Prepaid Ocean Services Limited':'ZAGGLE',
'Zee Entertainment Enterprises Limited':'ZEEL',
'Zee Media Corporation Limited':'ZEEMEDIA',
'Zenith Exports Limited':'ZENITHEXPO',
'Zensar Technologies Limited':'ZENSARTECH',
'Zen Technologies Limited':'ZENTEC',
'ZF Commercial Vehicle Control Systems India Limited':'ZFCVINDIA',
'Zim Laboratories Limited':'ZIMLAB',
'Zodiac Clothing Company Limited':'ZODIACLOTH',
'Zota Health Care LImited':'ZOTA',
'Zuari Agro Chemicals Limited':'ZUARI',
'ZUARI INDUSTRIES LIMITED':'ZUARIIND',
'Zydus Lifesciences Limited':'ZYDUSLIFE',
'Zydus Wellness Limited':'ZYDUSWELL'}
