from strategies import (
    rsi_macd_basic,
    ema_crossover,
    bollinger_band_breakout,
    stochastic_rsi,
    supertrend,
    adx_rsi,
    sma_ema_cross,
    rsi_ema_confluence,
    macd_histogram,
    atr_breakout,
    seven_twentyone_breakout,
    nine_thirty_pullback,
    turtlesoup,
    breakout_volatility,
    momentum_trend_volume,
    turtlesoup_pullback,
)

STRATEGY_MAP = {
    "RSI + MACD": rsi_macd_basic,
    "EMA Crossover": ema_crossover,
    "Bollinger Band Breakout": bollinger_band_breakout,
    "Stochastic RSI": stochastic_rsi,
    "Supertrend": supertrend,
    "ADX + RSI": adx_rsi,
    "SMA + EMA Cross": sma_ema_cross,
    "RSI + EMA Confluence": rsi_ema_confluence,
    "MACD Histogram Surge": macd_histogram,
    "ATR Breakout": atr_breakout,
    "7-21 Breakout": seven_twentyone_breakout,
    "9-30 Pullback": nine_thirty_pullback,
    "TurtleSoup": turtlesoup,
    "BreakoutVolatility": breakout_volatility,
    "MomentumTrendVolume": momentum_trend_volume,
    "TurtleSoupPullback": turtlesoup_pullback,
}
